import type { Metadata } from "next";
import { redirect } from "next/navigation";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { getAuthenticatedUser } from "@/lib/supabase/auth";
import { createClient } from "@/lib/supabase/server";
import { DashboardHeaderWrapper } from "@/components/app/dashboard-header-wrapper";
import { SharedFooter } from "@/components/app/shared-footer";
import { TravelFileActions } from "@/components/app/travel-file-actions";
import { TravelFileSectionEditor } from "@/components/app/travel-file-section-editor";
import { TravelNotesSection } from "@/components/app/travel-notes-section";
import { TravelPartyCard } from "@/components/app/travel-party-card";
import { WorkflowOverrideButton } from "@/components/app/workflow-override-button";
import { SendTmfButton } from "@/components/app/send-tmf-button";
import { getContact } from "@/lib/briitely/contacts";
import { Badge } from "@/components/core/ui/badge";
import { Button } from "@/components/core/ui/button";
import { formatStageLabel, formatStageBadgeVariant } from "@/lib/travel/stage-labels";
import { formatDueOrWaiting, formatReadableDate, formatReadableDateTime, formatDateOnly, formatCurrency, formatBoolean, isOverdue } from "@/lib/travel/format";
import type { TravelFile, TravelAction, TravelPayment, TravelConsultation, TravelActivity } from "@/lib/travel/types";

export const metadata: Metadata = { title: "Travel File — Inspired Vacations" };

function Panel({children}:{children:React.ReactNode}){return <div className="rounded-xl border bg-[#fffefa] p-5 shadow-sm">{children}</div>}
function Aside({eyebrow,title,text,action}:{eyebrow:string;title:string;text?:string;action?:React.ReactNode}){return <div><div className="flex items-start justify-between gap-2"><div><div className="text-[10px] font-semibold uppercase tracking-[0.12em] text-primary">{eyebrow}</div><div className="mt-1 font-serif text-xl leading-tight">{title}</div></div>{action}</div>{text&&<p className="mt-2 text-xs leading-relaxed text-muted-foreground">{text}</p>}</div>}
function Info({label,value}:{label:string;value:React.ReactNode}){return <div className="min-w-0"><div className="text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">{label}</div><div className="mt-1 text-sm font-medium text-foreground break-words">{value||"—"}</div></div>}
function SectionTitle({children}:{children:React.ReactNode}){return <h3 className="mb-3 border-b pb-2 text-xs font-semibold uppercase tracking-wide text-muted-foreground">{children}</h3>}
function getResponsibleName(action:TravelAction,profileMap:Record<string,string>){if(action.responsible_type==="client")return"Client";if(action.responsible_type==="system")return"System";if(action.responsible_type==="internal")return action.responsible_user_id?profileMap[action.responsible_user_id]??"Unassigned":"Unassigned";return"Unassigned"}
function ActionHistoryItem({action,profileMap}:{action:TravelAction;profileMap:Record<string,string>}){return <div className="py-2.5"><div className="flex flex-wrap items-center gap-2"><span className="text-sm font-medium">{action.title}</span><Badge variant="secondary" className="capitalize">{action.status}</Badge></div><div className="mt-1 flex flex-wrap gap-x-4 text-xs text-muted-foreground"><span>{getResponsibleName(action,profileMap)}</span><span>{formatDueOrWaiting(action.due_at,action.waiting_since)}</span>{action.completed_at&&<span>Completed {formatReadableDateTime(action.completed_at)}</span>}</div></div>}
function ActivityHistoryItem({activity}:{activity:TravelActivity&{actor_user:{id:string;full_name:string}|null}}){return <div className="py-2.5"><p className="text-sm">{activity.summary}</p><p className="mt-0.5 text-xs text-muted-foreground">{formatReadableDateTime(activity.created_at)}{activity.actor_user&&` · ${activity.actor_user.full_name}`}</p></div>}

export default async function TravelFilePage({params}:{params:Promise<{id:string}>}){
 const{user,error:authError}=await getAuthenticatedUser();if(authError||!user)redirect("/login?redirect=/dashboard");const{id}=await params;const supabase=await createClient();
 const{data:rawFile,error:fileError}=await supabase.from("travel_files").select(`*, current_action:travel_actions!current_action_id (*), assigned_advisor:profiles!assigned_advisor_id (id, full_name)`).eq("id",id).maybeSingle();
 if(fileError||!rawFile)return <div className="min-h-screen bg-[#f7f4ff]"><DashboardHeaderWrapper fullName={user.fullName} email={user.email} role={user.role}/><main className="mx-auto max-w-6xl p-6"><Panel>Travel File not found.</Panel></main></div>;
 const file=rawFile as unknown as TravelFile&{current_action:TravelAction|null;assigned_advisor:{id:string;full_name:string}|null};
 const[{data:rawActions},{data:rawPayments},{data:rawConsultations},{data:rawNotes},{data:rawActivity}]=await Promise.all([supabase.from("travel_actions").select("*").eq("travel_file_id",id).order("created_at",{ascending:false}),supabase.from("travel_payments").select("*").eq("travel_file_id",id).order("due_date",{ascending:true}),supabase.from("travel_consultations").select(`*, conducted_by_profile:profiles!conducted_by (id, full_name), assigned_advisor:profiles!assigned_advisor_id (id, full_name)`).eq("travel_file_id",id).order("consulted_at",{ascending:false}),supabase.from("travel_notes").select(`*, author:profiles!created_by (id, full_name)`).eq("travel_file_id",id).order("created_at",{ascending:false}),supabase.from("travel_activity").select(`*, actor_user:profiles!actor_user_id (id, full_name)`).eq("travel_file_id",id).order("created_at",{ascending:false})]);
 const actions=(rawActions as TravelAction[]|null)??[];const payments=(rawPayments as TravelPayment[]|null)??[];const consultations=(rawConsultations as unknown as (TravelConsultation&{conducted_by_profile:{id:string;full_name:string}|null;assigned_advisor:{id:string;full_name:string}|null})[]|null)??[];const activity=(rawActivity as unknown as (TravelActivity&{actor_user:{id:string;full_name:string}|null})[]|null)??[];
 const profileIds=new Set<string>();actions.forEach(a=>{if(a.responsible_user_id)profileIds.add(a.responsible_user_id)});let profileMap:Record<string,string>={};if(profileIds.size){const{data:p}=await supabase.from("profiles").select("id, full_name").in("id",[...profileIds]);profileMap=Object.fromEntries((p??[]).map(x=>[x.id,x.full_name]))}
 const sortedActions=[...actions].sort((a,b)=>{const aa=a.status==="active"||a.status==="pending",bb=b.status==="active"||b.status==="pending";if(aa&&!bb)return-1;if(!aa&&bb)return 1;return new Date(b.created_at).getTime()-new Date(a.created_at).getTime()});const currentAction=file.current_action;const isAdmin=user.role==="admin"||user.role==="super_admin";let contactEmail="",contactPhone="";if(file.briitely_contact_id){try{const c=await getContact(file.briitely_contact_id);contactEmail=c.email;contactPhone=c.phone}catch{}}
 const canSendTmf=currentAction?.action_code==="send_tmf_agreement"&&currentAction.status==="active"&&(isAdmin||currentAction.responsible_user_id===user.id);
 const edit=(section:"trip"|"inquiry"|"booking"|"insurance"|"assignment",values:Record<string,string|number|boolean|null|undefined>)=>user.isActive?<TravelFileSectionEditor travelFileId={file.id} updatedAt={file.updated_at} section={section} values={values}/>:undefined;
 return <div className="min-h-screen bg-[#f7f4ff]"><DashboardHeaderWrapper fullName={user.fullName} email={user.email} role={user.role}/><main className="mx-auto max-w-6xl space-y-4 px-4 py-6 sm:px-6 lg:px-8">
  <Button variant="ghost" asChild className="-ml-3"><Link href="/dashboard"><ArrowLeft className="h-4 w-4"/>Back to Dashboard</Link></Button>
  <div className="flex flex-col justify-between gap-4 px-1 pb-1 sm:flex-row sm:items-start"><div><div className="text-[10px] font-semibold uppercase tracking-[.16em] text-primary">Travel File</div><h1 className="mt-1 text-3xl font-semibold tracking-tight">{file.briitely_contact_id?<Link href={`/customers/${encodeURIComponent(file.briitely_contact_id)}`} className="hover:text-primary hover:underline">{file.client_name}</Link>:file.client_name}</h1><p className="mt-1 text-sm text-muted-foreground">{file.destination||"Trip details pending"}{file.departure_date?` · ${formatDateOnly(file.departure_date)}`:""}</p></div><div className="flex flex-wrap items-center gap-2"><Badge variant={formatStageBadgeVariant(file.stage)}>{formatStageLabel(file.stage)}</Badge><TravelFileActions travelFileId={file.id} clientName={file.client_name} destination={file.destination} tripType={file.trip_type} travelTimeframe={file.travel_timeframe} departureDate={file.departure_date} returnDate={file.return_date} numberOfAdults={file.number_of_adults} numberOfChildren={file.number_of_children} childrenAges={file.children_ages} budgetRange={file.budget_range} insuranceInterest={file.insurance_interest} specialConsiderations={file.special_requests} staffNotes={file.staff_notes} assignedAdvisorId={file.assigned_advisor_id} canEdit={user.isActive} canDelete={isAdmin} stage={file.stage} currentActionCode={currentAction?.action_code??null} currentActionStatus={currentAction?.status??null} previousNotes={(rawNotes as unknown as Array<{id:string;note_type:string;note_text:string;created_at:string;author:{id:string;full_name:string}|null}>)??[]}/></div></div>

  <Panel><div className="grid gap-5 md:grid-cols-[180px_1fr]"><Aside eyebrow="Workflow" title="Current action" text="The next step currently driving this travel file." action={isAdmin?<WorkflowOverrideButton travelFileId={file.id} currentStage={file.stage} currentActionCode={currentAction?.action_code??null} currentActionStatus={currentAction?.status??null} currentResponsibleType={currentAction?.responsible_type??null} currentResponsibleName={currentAction?getResponsibleName(currentAction,profileMap):null}/>:undefined}/><div>{currentAction?<><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-semibold">{currentAction.title}</h2><Badge variant="secondary" className="capitalize">{currentAction.action_role}</Badge><Badge variant="outline" className="capitalize">{currentAction.status}</Badge></div>{currentAction.description&&<p className="mt-1 text-sm text-muted-foreground">{currentAction.description}</p>}<div className="mt-4 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div className="grid flex-1 gap-4 sm:grid-cols-2"><Info label="Responsible" value={getResponsibleName(currentAction,profileMap)}/><Info label="Due / Waiting" value={<span className={isOverdue(currentAction.due_at)?"text-destructive":""}>{formatDueOrWaiting(currentAction.due_at,currentAction.waiting_since)}</span>}/></div>{canSendTmf&&<SendTmfButton travelFileId={file.id} clientName={file.client_name} email={contactEmail} phone={contactPhone} destination={file.destination} assignedAdvisorName={file.assigned_advisor?.full_name??null} agreementType={file.tmf_agreement_type} tmfAmount={file.tmf_amount} revisionsIncluded={file.revisions_included} agreementDate={new Date().toLocaleDateString("en-CA")}/>}</div></>:<p className="text-sm italic text-muted-foreground">No current action</p>}</div></div></Panel>

  <TravelPartyCard travelFileId={file.id}/>

  <Panel><div className="grid gap-5 md:grid-cols-[180px_1fr]"><Aside eyebrow="Trip" title="Trip details" text="Core trip information used throughout planning." action={edit("trip",{destination:file.destination,tripType:file.trip_type,travelTimeframe:file.travel_timeframe,departureDate:file.departure_date,returnDate:file.return_date,budgetRange:file.budget_range,specialConsiderations:file.special_requests})}/><div><SectionTitle>Trip information</SectionTitle><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Info label="Destination" value={file.destination}/><Info label="Trip type" value={file.trip_type}/><Info label="Travel timeframe" value={file.travel_timeframe}/><Info label="Budget" value={file.budget_range}/><Info label="Departure" value={file.departure_date?formatDateOnly(file.departure_date):"—"}/><Info label="Return" value={file.return_date?formatDateOnly(file.return_date):"—"}/><Info label="Travellers" value={file.number_of_travellers}/></div>{file.special_requests&&<div className="mt-5"><SectionTitle>Special considerations</SectionTitle><p className="text-sm text-foreground">{file.special_requests}</p></div>}</div></div></Panel>

  <Panel><div className="grid gap-5 md:grid-cols-[180px_1fr]"><Aside eyebrow="Team" title="Assignment" text="Who owns this file and where it sits in the workflow." action={edit("assignment",{assignedAdvisorId:file.assigned_advisor_id})}/><div><SectionTitle>Ownership</SectionTitle><div className="grid gap-4 sm:grid-cols-3"><Info label="Assigned advisor" value={file.assigned_advisor?.full_name??"Unassigned"}/><Info label="Stage" value={formatStageLabel(file.stage)}/><Info label="Phase" value={<span className="capitalize">{file.phase}</span>}/></div></div></div></Panel>

  {file.tmf_agreement_type&&<Panel><div className="grid gap-5 md:grid-cols-[180px_1fr]"><Aside eyebrow="Consultation" title="TMF details" text="Consultation outcome and Travel Management Fee details."/><div><SectionTitle>Agreement</SectionTitle><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Info label="Client fit" value="Yes"/><Info label="Agreement type" value={file.tmf_agreement_type==="ivt"?"IVT":"All-Inclusive"}/><Info label="TMF amount" value={formatCurrency(file.tmf_amount)}/><Info label="Assigned advisor" value={file.assigned_advisor?.full_name??"Unassigned"}/>{file.tmf_agreement_type==="ivt"&&<Info label="Revisions included" value={file.revisions_included}/>}</div></div></div></Panel>}

  <Panel><div className="grid gap-5 md:grid-cols-[180px_1fr]"><Aside eyebrow="Inquiry" title="Inquiry details" text="Where the inquiry came from and intake notes." action={edit("inquiry",{inquirySource:file.inquiry_source,intakeMethod:file.intake_method,referralDetail:file.referral_detail,eventDetail:file.event_detail,staffNotes:file.staff_notes,internalNotes:file.internal_notes})}/><div><SectionTitle>Source & intake</SectionTitle><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Info label="Source" value={file.inquiry_source}/><Info label="Received" value={formatReadableDate(file.inquiry_received_at)}/><Info label="Intake method" value={file.intake_method}/><Info label="Referral" value={file.referral_detail}/><Info label="Event" value={file.event_detail}/></div>{file.staff_notes&&<div className="mt-5"><SectionTitle>Staff notes</SectionTitle><p className="text-sm">{file.staff_notes}</p></div>}</div></div></Panel>

  <Panel><div className="grid gap-5 md:grid-cols-[180px_1fr]"><Aside eyebrow="Planning" title="Booking & planning" text="Proposal, booking and planning references." action={edit("booking",{proposalDueDate:file.proposal_due_date,dateBooked:file.date_booked,totalBookingValue:file.total_booking_value,tmfAmount:file.tmf_amount,ivtCustom:file.ivt_custom,clientbaseResCardId:file.clientbase_res_card_id,primaryBookingNumber:file.primary_booking_number,travefyProposalUrl:file.travefy_proposal_url,travefyTripPlanUrl:file.travefy_trip_plan_url})}/><div><SectionTitle>Booking information</SectionTitle><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Info label="Proposal due" value={file.proposal_due_date?formatDateOnly(file.proposal_due_date):"—"}/><Info label="Date booked" value={file.date_booked?formatDateOnly(file.date_booked):"—"}/><Info label="Booking value" value={formatCurrency(file.total_booking_value)}/><Info label="TMF" value={formatCurrency(file.tmf_amount)}/><Info label="IVT / custom" value={formatBoolean(file.ivt_custom)}/><Info label="ClientBase res card" value={file.clientbase_res_card_id}/><Info label="Booking number" value={file.primary_booking_number}/><Info label="Travefy proposal" value={file.travefy_proposal_url?<a className="text-primary hover:underline" href={file.travefy_proposal_url} target="_blank" rel="noreferrer">Open proposal</a>:"—"}/><Info label="Travefy trip plan" value={file.travefy_trip_plan_url?<a className="text-primary hover:underline" href={file.travefy_trip_plan_url} target="_blank" rel="noreferrer">Open trip plan</a>:"—"}/></div></div></div></Panel>

  <Panel><div className="grid gap-5 md:grid-cols-[180px_1fr]"><Aside eyebrow="Pre-trip" title="Insurance" text="Insurance, pre-trip meeting and registration status." action={edit("insurance",{insuranceInterest:file.insurance_interest,insuranceStatus:file.insurance_status,insuranceWaiverSigned:file.insurance_waiver_signed,pretripMeetingRequired:file.pretrip_meeting_required,pretripMeetingBookedAt:file.pretrip_meeting_booked_at,pretripCardSentAt:file.pretrip_card_sent_at,bookingRegistrationEligible:file.booking_registration_eligible,bookingRegistrationDoneAt:file.booking_registration_done_at})}/><div><SectionTitle>Insurance & pre-trip</SectionTitle><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Info label="Insurance preference" value={file.insurance_interest}/><Info label="Status" value={<span className="capitalize">{file.insurance_status}</span>}/><Info label="Waiver signed" value={formatBoolean(file.insurance_waiver_signed)}/><Info label="Meeting required" value={formatBoolean(file.pretrip_meeting_required)}/><Info label="Meeting booked" value={file.pretrip_meeting_booked_at?formatReadableDateTime(file.pretrip_meeting_booked_at):"—"}/><Info label="Card sent" value={file.pretrip_card_sent_at?formatReadableDateTime(file.pretrip_card_sent_at):"—"}/><Info label="Registration eligible" value={formatBoolean(file.booking_registration_eligible)}/><Info label="Registration done" value={file.booking_registration_done_at?formatReadableDateTime(file.booking_registration_done_at):"—"}/></div></div></div></Panel>

  <TravelNotesSection travelFileId={file.id} legacyStaffNotes={file.staff_notes} isAdmin={isAdmin} currentUserId={user.id}/>

  <Panel><div className="grid gap-5 md:grid-cols-[180px_1fr]"><Aside eyebrow="Financial" title="Payments" text="Payment schedule and current status."/><div>{payments.length===0?<p className="text-sm italic text-muted-foreground">No payments recorded.</p>:<div className="divide-y">{payments.map(p=><div key={p.id} className="flex flex-wrap items-center justify-between gap-2 py-3"><div><span className="text-sm font-medium capitalize">{p.payment_type}</span>{p.description&&<span className="ml-2 text-sm text-muted-foreground">{p.description}</span>}<p className="text-xs text-muted-foreground">Due {formatDateOnly(p.due_date)}</p></div><div className="flex items-center gap-3"><span className="text-sm font-medium">{formatCurrency(p.amount)}</span><Badge variant="outline" className="capitalize">{p.status}</Badge></div></div>)}</div>}</div></div></Panel>

  <Panel><div className="grid gap-5 md:grid-cols-[180px_1fr]"><Aside eyebrow="History" title="Consultations" text="Completed consultation records."/><div>{consultations.length===0?<p className="text-sm italic text-muted-foreground">No consultations recorded.</p>:<div className="divide-y">{consultations.map(c=><div key={c.id} className="py-3"><div className="flex flex-wrap items-center gap-2"><span className="text-sm font-medium">{formatReadableDate(c.consulted_at)}</span><Badge variant="secondary" className="capitalize">{c.outcome.replace(/_/g," ")}</Badge><span className="text-xs text-muted-foreground">by {c.conducted_by_profile?.full_name??"Unknown"}</span></div>{c.discussion_summary&&<p className="mt-1 text-sm text-muted-foreground">{c.discussion_summary}</p>}</div>)}</div>}</div></div></Panel>

  <Panel><div className="grid gap-5 md:grid-cols-[180px_1fr]"><Aside eyebrow="History" title="Actions" text="Workflow actions completed or waiting on this file."/><div>{sortedActions.length===0?<p className="text-sm italic text-muted-foreground">No actions recorded.</p>:<div className="divide-y">{sortedActions.slice(0,4).map(a=><ActionHistoryItem key={a.id} action={a} profileMap={profileMap}/>)}{sortedActions.length>4&&<details><summary className="cursor-pointer py-3 text-sm font-medium text-primary">See more actions ({sortedActions.length-4})</summary><div className="divide-y border-t">{sortedActions.slice(4).map(a=><ActionHistoryItem key={a.id} action={a} profileMap={profileMap}/>)}</div></details>}</div>}</div></div></Panel>

  <Panel><div className="grid gap-5 md:grid-cols-[180px_1fr]"><Aside eyebrow="History" title="Activity" text="Chronological audit trail for this travel file."/><div>{activity.length===0?<p className="text-sm italic text-muted-foreground">No activity recorded.</p>:<div className="divide-y">{activity.slice(0,4).map(a=><ActivityHistoryItem key={a.id} activity={a}/>)}{activity.length>4&&<details><summary className="cursor-pointer py-3 text-sm font-medium text-primary">See more activity ({activity.length-4})</summary><div className="divide-y border-t">{activity.slice(4).map(a=><ActivityHistoryItem key={a.id} activity={a}/>)}</div></details>}</div>}</div></div></Panel>
 </main><SharedFooter maxWidth="max-w-6xl" label="Travel File"/></div>
}
