import type { Metadata } from "next";
import { redirect } from "next/navigation";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { getAuthenticatedUser } from "@/lib/supabase/auth";
import { createClient } from "@/lib/supabase/server";
import { DashboardHeaderWrapper } from "@/components/app/dashboard-header-wrapper";
import { SharedFooter } from "@/components/app/shared-footer";
import { TravelFileActions } from "@/components/app/travel-file-actions";
import { TravelFileSectionEditor } from "@/components/app/travel-file-section-editor";
import { TravelNotesSection } from "@/components/app/travel-notes-section";
import { TravelPartyCard } from "@/components/app/travel-party-card";
import { WorkflowOverrideButton } from "@/components/app/workflow-override-button";
import { SendTmfButton } from "@/components/app/send-tmf-button";
import { getContact } from "@/lib/briitely/contacts";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/core/ui/card";
import { Badge } from "@/components/core/ui/badge";
import { Button } from "@/components/core/ui/button";
import { formatStageLabel, formatStageBadgeVariant } from "@/lib/travel/stage-labels";
import { formatDueOrWaiting, formatReadableDate, formatReadableDateTime, formatDateOnly, formatCurrency, formatBoolean, isOverdue } from "@/lib/travel/format";
import type { TravelFile, TravelAction, TravelPayment, TravelConsultation, TravelActivity } from "@/lib/travel/types";

export const metadata: Metadata = { title: "Travel File — Inspired Vacations" };
function InfoRow({label,value}:{label:string;value:React.ReactNode}){return <div className="min-w-0"><p className="text-[11px] font-medium uppercase tracking-wide text-muted-foreground">{label}</p><div className="mt-1 text-sm font-medium text-foreground break-words">{value||"—"}</div></div>}
function SectionHeader({title,action}:{title:string;action?:React.ReactNode}){return <CardHeader className="flex flex-row items-center justify-between gap-3 border-b border-border/60 px-5 py-3"><CardTitle className="text-sm font-semibold">{title}</CardTitle>{action}</CardHeader>}
function getResponsibleName(action:TravelAction,profileMap:Record<string,string>){if(action.responsible_type==="client")return"Client";if(action.responsible_type==="system")return"System";if(action.responsible_type==="internal")return action.responsible_user_id?profileMap[action.responsible_user_id]??"Unassigned":"Unassigned";return"Unassigned"}
function ActionHistoryItem({action,profileMap}:{action:TravelAction;profileMap:Record<string,string>}){return <div className="py-2.5"><div className="flex flex-wrap items-center gap-2"><span className="text-sm font-medium">{action.title}</span><Badge variant="secondary" className="capitalize">{action.status}</Badge></div><div className="mt-1 flex flex-wrap gap-x-4 text-xs text-muted-foreground"><span>{getResponsibleName(action,profileMap)}</span><span>{formatDueOrWaiting(action.due_at,action.waiting_since)}</span>{action.completed_at&&<span>Completed {formatReadableDateTime(action.completed_at)}</span>}</div></div>}
function ActivityHistoryItem({activity}:{activity:TravelActivity&{actor_user:{id:string;full_name:string}|null}}){return <div className="py-2.5"><p className="text-sm">{activity.summary}</p><p className="mt-0.5 text-xs text-muted-foreground">{formatReadableDateTime(activity.created_at)}{activity.actor_user&&` · ${activity.actor_user.full_name}`}</p></div>}

export default async function TravelFilePage({params}:{params:Promise<{id:string}>}){
 const{user,error:authError}=await getAuthenticatedUser();if(authError||!user)redirect("/login?redirect=/dashboard");const{id}=await params;const supabase=await createClient();
 const{data:rawFile,error:fileError}=await supabase.from("travel_files").select(`*, current_action:travel_actions!current_action_id (*), assigned_advisor:profiles!assigned_advisor_id (id, full_name)`).eq("id",id).maybeSingle();
 if(fileError||!rawFile)return <div className="min-h-screen bg-muted/20"><DashboardHeaderWrapper fullName={user.fullName} email={user.email} role={user.role}/><main className="mx-auto max-w-6xl p-6"><Card><CardContent className="p-6">Travel File not found.</CardContent></Card></main></div>;
 const file=rawFile as unknown as TravelFile&{current_action:TravelAction|null;assigned_advisor:{id:string;full_name:string}|null};
 const[{data:rawActions},{data:rawPayments},{data:rawConsultations},{data:rawNotes},{data:rawActivity}]=await Promise.all([supabase.from("travel_actions").select("*").eq("travel_file_id",id).order("created_at",{ascending:false}),supabase.from("travel_payments").select("*").eq("travel_file_id",id).order("due_date",{ascending:true}),supabase.from("travel_consultations").select(`*, conducted_by_profile:profiles!conducted_by (id, full_name), assigned_advisor:profiles!assigned_advisor_id (id, full_name)`).eq("travel_file_id",id).order("consulted_at",{ascending:false}),supabase.from("travel_notes").select(`*, author:profiles!created_by (id, full_name)`).eq("travel_file_id",id).order("created_at",{ascending:false}),supabase.from("travel_activity").select(`*, actor_user:profiles!actor_user_id (id, full_name)`).eq("travel_file_id",id).order("created_at",{ascending:false})]);
 const actions=(rawActions as TravelAction[]|null)??[];const payments=(rawPayments as TravelPayment[]|null)??[];const consultations=(rawConsultations as unknown as (TravelConsultation&{conducted_by_profile:{id:string;full_name:string}|null;assigned_advisor:{id:string;full_name:string}|null})[]|null)??[];const activity=(rawActivity as unknown as (TravelActivity&{actor_user:{id:string;full_name:string}|null})[]|null)??[];
 const profileIds=new Set<string>();actions.forEach(a=>{if(a.responsible_user_id)profileIds.add(a.responsible_user_id)});let profileMap:Record<string,string>={};if(profileIds.size){const{data:p}=await supabase.from("profiles").select("id, full_name").in("id",[...profileIds]);profileMap=Object.fromEntries((p??[]).map(x=>[x.id,x.full_name]))}
 const sortedActions=[...actions].sort((a,b)=>{const aa=a.status==="active"||a.status==="pending",bb=b.status==="active"||b.status==="pending";if(aa&&!bb)return-1;if(!aa&&bb)return 1;return new Date(b.created_at).getTime()-new Date(a.created_at).getTime()});const currentAction=file.current_action;const isAdmin=user.role==="admin"||user.role==="super_admin";let contactEmail="",contactPhone="";if(file.briitely_contact_id){try{const c=await getContact(file.briitely_contact_id);contactEmail=c.email;contactPhone=c.phone}catch{}}
 const canSendTmf=currentAction?.action_code==="send_tmf_agreement"&&currentAction.status==="active"&&(isAdmin||currentAction.responsible_user_id===user.id);
 const edit=(section:"trip"|"inquiry"|"booking"|"insurance"|"assignment",values:Record<string,string|number|boolean|null|undefined>)=>user.isActive?<TravelFileSectionEditor travelFileId={file.id} updatedAt={file.updated_at} section={section} values={values}/>:undefined;
 return <div className="min-h-screen bg-muted/20"><DashboardHeaderWrapper fullName={user.fullName} email={user.email} role={user.role}/><main className="mx-auto max-w-6xl space-y-4 px-4 py-6 sm:px-6 lg:px-8">
  <Button variant="ghost" asChild className="-ml-3"><Link href="/dashboard"><ArrowLeft className="h-4 w-4"/>Back to Dashboard</Link></Button>
  <Card className="border-primary/20 shadow-sm"><CardContent className="p-5"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-primary">Travel File</p><h1 className="mt-1 text-2xl font-bold">{file.briitely_contact_id?<Link href={`/customers/${encodeURIComponent(file.briitely_contact_id)}`} className="hover:text-primary hover:underline">{file.client_name}</Link>:file.client_name}</h1><p className="mt-1 text-sm text-muted-foreground">{file.destination||"Trip details pending"}{file.departure_date?` · ${formatDateOnly(file.departure_date)}`:""}</p></div><div className="flex flex-wrap items-center gap-2"><Badge variant={formatStageBadgeVariant(file.stage)}>{formatStageLabel(file.stage)}</Badge><TravelFileActions travelFileId={file.id} clientName={file.client_name} destination={file.destination} tripType={file.trip_type} travelTimeframe={file.travel_timeframe} departureDate={file.departure_date} returnDate={file.return_date} numberOfAdults={file.number_of_adults} numberOfChildren={file.number_of_children} childrenAges={file.children_ages} budgetRange={file.budget_range} insuranceInterest={file.insurance_interest} specialConsiderations={file.special_requests} staffNotes={file.staff_notes} assignedAdvisorId={file.assigned_advisor_id} canEdit={user.isActive} canDelete={isAdmin} stage={file.stage} currentActionCode={currentAction?.action_code??null} currentActionStatus={currentAction?.status??null} previousNotes={(rawNotes as unknown as Array<{id:string;note_type:string;note_text:string;created_at:string;author:{id:string;full_name:string}|null}>)??[]}/></div></div></CardContent></Card>
  <Card><SectionHeader title="Current Action" action={isAdmin?<WorkflowOverrideButton travelFileId={file.id} currentStage={file.stage} currentActionCode={currentAction?.action_code??null} currentActionStatus={currentAction?.status??null} currentResponsibleType={currentAction?.responsible_type??null} currentResponsibleName={currentAction?getResponsibleName(currentAction,profileMap):null}/>:undefined}/><CardContent className="p-5">{currentAction?<div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-semibold">{currentAction.title}</h2><Badge variant="secondary" className="capitalize">{currentAction.action_role}</Badge><Badge variant="outline" className="capitalize">{currentAction.status}</Badge></div>{currentAction.description&&<p className="mt-1 text-sm text-muted-foreground">{currentAction.description}</p>}<div className="mt-3 grid gap-4 sm:grid-cols-2"><InfoRow label="Responsible" value={getResponsibleName(currentAction,profileMap)}/><InfoRow label="Due / Waiting" value={<span className={isOverdue(currentAction.due_at)?"text-destructive":""}>{formatDueOrWaiting(currentAction.due_at,currentAction.waiting_since)}</span>}/></div></div>{canSendTmf&&<SendTmfButton travelFileId={file.id} clientName={file.client_name} email={contactEmail} phone={contactPhone} destination={file.destination} assignedAdvisorName={file.assigned_advisor?.full_name??null} agreementType={file.tmf_agreement_type} tmfAmount={file.tmf_amount} revisionsIncluded={file.revisions_included} agreementDate={new Date().toLocaleDateString("en-CA")}/>}</div>:<p className="text-sm italic text-muted-foreground">No current action</p>}</CardContent></Card>
  <TravelPartyCard travelFileId={file.id}/>
  <Card><SectionHeader title="Trip Details" action={edit("trip",{destination:file.destination,tripType:file.trip_type,travelTimeframe:file.travel_timeframe,departureDate:file.departure_date,returnDate:file.return_date,budgetRange:file.budget_range,specialConsiderations:file.special_requests})}/><CardContent className="p-5"><div className="grid gap-x-8 gap-y-4 sm:grid-cols-2 lg:grid-cols-4"><InfoRow label="Destination" value={file.destination}/><InfoRow label="Trip Type" value={file.trip_type}/><InfoRow label="Travel Timeframe" value={file.travel_timeframe}/><InfoRow label="Budget" value={file.budget_range}/><InfoRow label="Departure" value={file.departure_date?formatDateOnly(file.departure_date):"—"}/><InfoRow label="Return" value={file.return_date?formatDateOnly(file.return_date):"—"}/><InfoRow label="Travellers" value={file.number_of_travellers}/><div className="sm:col-span-2 lg:col-span-4"><InfoRow label="Special Considerations" value={file.special_requests}/></div></div></CardContent></Card>
  <Card><SectionHeader title="Assignment" action={edit("assignment",{assignedAdvisorId:file.assigned_advisor_id})}/><CardContent className="p-5"><div className="grid gap-4 sm:grid-cols-3"><InfoRow label="Assigned Advisor" value={file.assigned_advisor?.full_name??"Unassigned"}/><InfoRow label="Stage" value={formatStageLabel(file.stage)}/><InfoRow label="Phase" value={<span className="capitalize">{file.phase}</span>}/></div></CardContent></Card>
  {file.tmf_agreement_type&&<Card><SectionHeader title="Consultation / TMF Details"/><CardContent className="p-5"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><InfoRow label="Client Fit" value="Yes"/><InfoRow label="Agreement" value={file.tmf_agreement_type==="ivt"?"IVT":"All-Inclusive"}/><InfoRow label="TMF Amount" value={formatCurrency(file.tmf_amount)}/><InfoRow label="Advisor" value={file.assigned_advisor?.full_name??"Unassigned"}/>{file.tmf_agreement_type==="ivt"&&<InfoRow label="Revisions" value={file.revisions_included}/>}</div></CardContent></Card>}
  <Card><SectionHeader title="Inquiry Details" action={edit("inquiry",{inquirySource:file.inquiry_source,intakeMethod:file.intake_method,referralDetail:file.referral_detail,eventDetail:file.event_detail,staffNotes:file.staff_notes,internalNotes:file.internal_notes})}/><CardContent className="p-5"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><InfoRow label="Source" value={file.inquiry_source}/><InfoRow label="Received" value={formatReadableDate(file.inquiry_received_at)}/><InfoRow label="Intake Method" value={file.intake_method}/><InfoRow label="Referral" value={file.referral_detail}/><InfoRow label="Event" value={file.event_detail}/><div className="sm:col-span-2"><InfoRow label="Staff Notes" value={file.staff_notes}/></div></div></CardContent></Card>
  <Card><SectionHeader title="Booking & Planning" action={edit("booking",{proposalDueDate:file.proposal_due_date,dateBooked:file.date_booked,totalBookingValue:file.total_booking_value,tmfAmount:file.tmf_amount,ivtCustom:file.ivt_custom,clientbaseResCardId:file.clientbase_res_card_id,primaryBookingNumber:file.primary_booking_number,travefyProposalUrl:file.travefy_proposal_url,travefyTripPlanUrl:file.travefy_trip_plan_url})}/><CardContent className="p-5"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><InfoRow label="Proposal Due" value={file.proposal_due_date?formatDateOnly(file.proposal_due_date):"—"}/><InfoRow label="Date Booked" value={file.date_booked?formatDateOnly(file.date_booked):"—"}/><InfoRow label="Booking Value" value={formatCurrency(file.total_booking_value)}/><InfoRow label="TMF" value={formatCurrency(file.tmf_amount)}/><InfoRow label="IVT / Custom" value={formatBoolean(file.ivt_custom)}/><InfoRow label="ClientBase Res Card" value={file.clientbase_res_card_id}/><InfoRow label="Booking Number" value={file.primary_booking_number}/><InfoRow label="Travefy Proposal" value={file.travefy_proposal_url?<a className="text-primary hover:underline" href={file.travefy_proposal_url} target="_blank" rel="noreferrer">Open proposal</a>:"—"}/><InfoRow label="Travefy Trip Plan" value={file.travefy_trip_plan_url?<a className="text-primary hover:underline" href={file.travefy_trip_plan_url} target="_blank" rel="noreferrer">Open trip plan</a>:"—"}/></div></CardContent></Card>
  <Card><SectionHeader title="Insurance & Pre-Trip" action={edit("insurance",{insuranceInterest:file.insurance_interest,insuranceStatus:file.insurance_status,insuranceWaiverSigned:file.insurance_waiver_signed,pretripMeetingRequired:file.pretrip_meeting_required,pretripMeetingBookedAt:file.pretrip_meeting_booked_at,pretripCardSentAt:file.pretrip_card_sent_at,bookingRegistrationEligible:file.booking_registration_eligible,bookingRegistrationDoneAt:file.booking_registration_done_at})}/><CardContent className="p-5"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><InfoRow label="Insurance Preference" value={file.insurance_interest}/><InfoRow label="Status" value={<span className="capitalize">{file.insurance_status}</span>}/><InfoRow label="Waiver Signed" value={formatBoolean(file.insurance_waiver_signed)}/><InfoRow label="Pre-Trip Meeting" value={formatBoolean(file.pretrip_meeting_required)}/><InfoRow label="Meeting Booked" value={file.pretrip_meeting_booked_at?formatReadableDateTime(file.pretrip_meeting_booked_at):"—"}/><InfoRow label="Card Sent" value={file.pretrip_card_sent_at?formatReadableDateTime(file.pretrip_card_sent_at):"—"}/><InfoRow label="Registration Eligible" value={formatBoolean(file.booking_registration_eligible)}/><InfoRow label="Registration Done" value={file.booking_registration_done_at?formatReadableDateTime(file.booking_registration_done_at):"—"}/></div></CardContent></Card>
  <TravelNotesSection travelFileId={file.id} legacyStaffNotes={file.staff_notes} isAdmin={isAdmin} currentUserId={user.id}/>
  <Card><SectionHeader title="Payments"/><CardContent className="px-5 py-2">{payments.length===0?<p className="py-3 text-sm italic text-muted-foreground">No payments recorded.</p>:<div className="divide-y">{payments.map(p=><div key={p.id} className="flex flex-wrap items-center justify-between gap-2 py-3"><div><span className="text-sm font-medium capitalize">{p.payment_type}</span>{p.description&&<span className="ml-2 text-sm text-muted-foreground">{p.description}</span>}<p className="text-xs text-muted-foreground">Due {formatDateOnly(p.due_date)}</p></div><div className="flex items-center gap-3"><span className="text-sm font-medium">{formatCurrency(p.amount)}</span><Badge variant="outline" className="capitalize">{p.status}</Badge></div></div>)}</div>}</CardContent></Card>
  <Card><SectionHeader title="Consultations"/><CardContent className="px-5 py-2">{consultations.length===0?<p className="py-3 text-sm italic text-muted-foreground">No consultations recorded.</p>:<div className="divide-y">{consultations.map(c=><div key={c.id} className="py-3"><div className="flex flex-wrap items-center gap-2"><span className="text-sm font-medium">{formatReadableDate(c.consulted_at)}</span><Badge variant="secondary" className="capitalize">{c.outcome.replace(/_/g," ")}</Badge><span className="text-xs text-muted-foreground">by {c.conducted_by_profile?.full_name??"Unknown"}</span></div>{c.discussion_summary&&<p className="mt-1 text-sm text-muted-foreground">{c.discussion_summary}</p>}</div>)}</div>}</CardContent></Card>
  <Card><SectionHeader title="Actions"/><CardContent className="px-5 py-2">{sortedActions.length===0?<p className="py-3 text-sm italic text-muted-foreground">No actions recorded.</p>:<div className="divide-y">{sortedActions.slice(0,4).map(a=><ActionHistoryItem key={a.id} action={a} profileMap={profileMap}/>)}{sortedActions.length>4&&<details><summary className="cursor-pointer py-3 text-sm font-medium text-primary">See more actions ({sortedActions.length-4})</summary><div className="divide-y border-t">{sortedActions.slice(4).map(a=><ActionHistoryItem key={a.id} action={a} profileMap={profileMap}/>)}</div></details>}</div>}</CardContent></Card>
  <Card><SectionHeader title="Activity"/><CardContent className="px-5 py-2">{activity.length===0?<p className="py-3 text-sm italic text-muted-foreground">No activity recorded.</p>:<div className="divide-y">{activity.slice(0,4).map(a=><ActivityHistoryItem key={a.id} activity={a}/>)}{activity.length>4&&<details><summary className="cursor-pointer py-3 text-sm font-medium text-primary">See more activity ({activity.length-4})</summary><div className="divide-y border-t">{activity.slice(4).map(a=><ActivityHistoryItem key={a.id} activity={a}/>)}</div></details>}</div>}</CardContent></Card>
 </main><SharedFooter maxWidth="max-w-6xl" label="Travel File"/></div>
}
