import { NextResponse } from "next/server";
import { getAuthenticatedUser } from "@/lib/supabase/auth";
import { createClient } from "@/lib/supabase/server";
import { syncPaymentBatchTask } from "@/lib/travel/payment-tasks";

const PAYMENT_TYPES = new Set(["deposit", "installment", "final", "other"]);
const VISIBLE_PAYMENT_STATUSES = new Set(["upcoming", "paid"]);
const PROCESSING_METHODS = new Set(["manual", "supplier_auto"]);

type PaymentBody = { paymentId?: string; paymentType?: string; description?: string; supplier?: string; confirmationNumber?: string; amount?: number|string|null; currency?: string; dueDate?: string; status?: string; processedDate?: string|null; cardLastFour?: string; processingMethod?: string };
async function context(){const{user}=await getAuthenticatedUser();if(!user||!user.isActive)return null;if(!["staff","admin","super_admin"].includes(user.role))return null;return{user,db:await createClient()}}
function clean(value:unknown){return typeof value==="string"&&value.trim()?value.trim():null}
function parseDetails(value:unknown){if(typeof value!=="string"||!value.trim())return{supplier:null,cardLastFour:null,processingMethod:"manual"};try{const parsed=JSON.parse(value)as{supplier?:unknown;cardLastFour?:unknown;processingMethod?:unknown};const method=clean(parsed.processingMethod);return{supplier:clean(parsed.supplier),cardLastFour:clean(parsed.cardLastFour),processingMethod:method&&PROCESSING_METHODS.has(method)?method:"manual"}}catch{return{supplier:null,cardLastFour:null,processingMethod:"manual"}}}
function serializeDetails(supplier:string|null,cardLastFour:string|null,processingMethod:string){return JSON.stringify({supplier,cardLastFour,processingMethod})}
function sevenDaysBefore(dateValue:string){const date=new Date(`${dateValue}T12:00:00.000Z`);date.setUTCDate(date.getUTCDate()-7);return date.toISOString().slice(0,10)}
function normalizePayment(row:any){const details=parseDetails(row.details);return{...row,supplier:details.supplier,card_last_four:details.cardLastFour,processing_method:details.processingMethod,confirmation_number:row.external_reference??null}}
function validate(body:PaymentBody){const paymentType=clean(body.paymentType)??"other",description=clean(body.description),dueDate=clean(body.dueDate),status=clean(body.status)??"upcoming",cardLastFour=clean(body.cardLastFour),processingMethod=clean(body.processingMethod)??"manual",amount=body.amount===null||body.amount===""||body.amount===undefined?null:Number(body.amount);if(!description)return{error:"Reservation / payment description is required."}as const;if(!dueDate)return{error:"Due date is required."}as const;if(!PAYMENT_TYPES.has(paymentType))return{error:"Choose a valid payment type."}as const;if(!VISIBLE_PAYMENT_STATUSES.has(status))return{error:"Choose a valid payment status."}as const;if(!PROCESSING_METHODS.has(processingMethod))return{error:"Choose a valid processing method."}as const;if(amount!==null&&(!Number.isFinite(amount)||amount<0))return{error:"Enter a valid payment amount."}as const;if(cardLastFour&&!/^\d{4}$/.test(cardLastFour))return{error:"Card last four must be exactly 4 digits."}as const;return{value:{payment_type:paymentType,description,supplier:clean(body.supplier),confirmationNumber:clean(body.confirmationNumber),amount,currency:(clean(body.currency)??"CAD").toUpperCase(),due_date:dueDate,status,cardLastFour,processingMethod,processedDate:clean(body.processedDate),clientNotificationDate:sevenDaysBefore(dueDate)}}as const}
export async function GET(_request:Request,{params}:{params:Promise<{travelFileId:string}>}){const ctx=await context();if(!ctx)return NextResponse.json({error:"Authentication required."},{status:401});const{travelFileId}=await params;const{data,error}=await ctx.db.from("travel_payments").select("id,payment_type,description,amount,currency,due_date,client_notification_date,status,processed_at,created_at,details,external_reference").eq("travel_file_id",travelFileId).order("due_date",{ascending:true});if(error)return NextResponse.json({error:"Could not load payments."},{status:500});return NextResponse.json({payments:(data??[]).map(normalizePayment)})}
export async function POST(request:Request,{params}:{params:Promise<{travelFileId:string}>}){const ctx=await context();if(!ctx)return NextResponse.json({error:"Authentication required."},{status:401});const{travelFileId}=await params;const body=await request.json().catch(()=>null)as PaymentBody|null;if(!body)return NextResponse.json({error:"Payment details are required."},{status:400});const checked=validate(body);if("error"in checked)return NextResponse.json({error:checked.error},{status:400});const v=checked.value,now=new Date().toISOString(),processedAt=v.status==="paid"?(v.processedDate?`${v.processedDate}T12:00:00.000Z`:now):null;const{data,error}=await ctx.db.from("travel_payments").insert({travel_file_id:travelFileId,payment_type:v.payment_type,description:v.description,amount:v.amount,currency:v.currency,due_date:v.due_date,client_notification_date:v.clientNotificationDate,status:v.status,details:serializeDetails(v.supplier,v.cardLastFour,v.processingMethod),external_reference:v.confirmationNumber,processed_at:processedAt,processed_by:v.status==="paid"?ctx.user.id:null}).select("id,payment_type,description,amount,currency,due_date,client_notification_date,status,processed_at,created_at,details,external_reference").single();if(error||!data)return NextResponse.json({error:error?.message??"Could not add payment."},{status:500});await syncPaymentBatchTask(ctx.db,travelFileId,v.due_date);return NextResponse.json({payment:normalizePayment(data)},{status:201})}
export async function PATCH(request:Request,{params}:{params:Promise<{travelFileId:string}>}){const ctx=await context();if(!ctx)return NextResponse.json({error:"Authentication required."},{status:401});const{travelFileId}=await params;const body=await request.json().catch(()=>null)as PaymentBody|null;if(!body?.paymentId)return NextResponse.json({error:"Payment is required."},{status:400});const checked=validate(body);if("error"in checked)return NextResponse.json({error:checked.error},{status:400});const v=checked.value,now=new Date().toISOString();const{data:existing}=await ctx.db.from("travel_payments").select("processed_at,due_date").eq("id",body.paymentId).eq("travel_file_id",travelFileId).maybeSingle();if(!existing)return NextResponse.json({error:"Payment not found."},{status:404});const processedAt=v.status==="paid"?(v.processedDate?`${v.processedDate}T12:00:00.000Z`:existing.processed_at??now):null;const{data,error}=await ctx.db.from("travel_payments").update({payment_type:v.payment_type,description:v.description,amount:v.amount,currency:v.currency,due_date:v.due_date,client_notification_date:v.clientNotificationDate,status:v.status,details:serializeDetails(v.supplier,v.cardLastFour,v.processingMethod),external_reference:v.confirmationNumber,processed_at:processedAt,processed_by:v.status==="paid"?ctx.user.id:null,updated_at:now}).eq("id",body.paymentId).eq("travel_file_id",travelFileId).select("id,payment_type,description,amount,currency,due_date,client_notification_date,status,processed_at,created_at,details,external_reference").single();if(error||!data)return NextResponse.json({error:error?.message??"Could not update payment."},{status:500});await syncPaymentBatchTask(ctx.db,travelFileId,v.due_date);if(existing.due_date&&existing.due_date!==v.due_date)await syncPaymentBatchTask(ctx.db,travelFileId,existing.due_date);return NextResponse.json({payment:normalizePayment(data)})}
export async function DELETE(request:Request,{params}:{params:Promise<{travelFileId:string}>}){const ctx=await context();if(!ctx)return NextResponse.json({error:"Authentication required."},{status:401});const{travelFileId}=await params;const body=await request.json().catch(()=>null)as{paymentId?:string}|null;if(!body?.paymentId)return NextResponse.json({error:"Payment is required."},{status:400});const{data:existing}=await ctx.db.from("travel_payments").select("due_date").eq("id",body.paymentId).eq("travel_file_id",travelFileId).maybeSingle();const{error}=await ctx.db.from("travel_payments").delete().eq("id",body.paymentId).eq("travel_file_id",travelFileId);if(error)return NextResponse.json({error:error.message},{status:500});if(existing?.due_date)await syncPaymentBatchTask(ctx.db,travelFileId,existing.due_date);return NextResponse.json({deleted:true})}
