import{NextResponse}from"next/server";import{getAuthenticatedUser}from"@/lib/supabase/auth";import{createClient}from"@/lib/supabase/server";
async function ctx(){const{user}=await getAuthenticatedUser();if(!user||!user.isActive||!["staff","admin","super_admin"].includes(user.role))return null;return{user,db:await createClient()}}
function profile(member:any){return Array.isArray(member?.traveller_profiles)?member.traveller_profiles[0]:member?.traveller_profiles}
export async function POST(_request:Request,{params}:{params:Promise<{travelFileId:string}>}){const c=await ctx();if(!c)return NextResponse.json({error:"Authentication required."},{status:401});const{travelFileId}=await params;const webhookUrl=process.env.BRIITELY_PRETRIP_EMAIL_SCHEDULE_WEBHOOK_URL?.trim();if(!webhookUrl)return NextResponse.json({error:"BRIITELY_PRETRIP_EMAIL_SCHEDULE_WEBHOOK_URL is not configured."},{status:500});
const[{data:file,error:fileError},{data:emails,error:emailError},{data:party,error:partyError}]=await Promise.all([
c.db.from("travel_files").select("id,client_name,destination,trip_type,departure_date,return_date,assigned_advisor_id,briitely_contact_id").eq("id",travelFileId).maybeSingle(),
c.db.from("travel_pretrip_emails").select("email_code,email_name,enabled,scheduled_date,timing_note,sequence_order,sent_at").eq("travel_file_id",travelFileId).order("sequence_order",{ascending:true}),
c.db.from("travel_file_travellers").select("id,traveller_role,receive_trip_communications,traveller_profiles:traveller_profile_id(briitely_contact_id,first_name,last_name,preferred_name,email)").eq("travel_file_id",travelFileId).order("created_at",{ascending:true})
]);if(fileError||!file)return NextResponse.json({error:"Travel File not found."},{status:404});if(emailError||partyError)return NextResponse.json({error:"Could not prepare the pre-trip email schedule."},{status:500});
const recipients=(party??[]).filter((m:any)=>m.traveller_role==="primary"||m.receive_trip_communications).map((m:any)=>{const p=profile(m);return{party_member_id:m.id,contact_id:p?.briitely_contact_id??null,name:[p?.preferred_name||p?.first_name,p?.last_name].filter(Boolean).join(" ")||"Client",first_name:p?.preferred_name||p?.first_name||"there",email:p?.email??null,is_primary:m.traveller_role==="primary"}}).filter((r:any)=>Boolean(r.email));
if(!recipients.length)return NextResponse.json({error:"No trip communication recipients have an email address."},{status:400});
const schedule=(emails??[]).map((e:any)=>({email_code:e.email_code,email_name:e.email_name,enabled:e.enabled,scheduled_date:e.scheduled_date,timing_note:e.timing_note,sequence_order:e.sequence_order,sent_at:e.sent_at}));
const payload={event:"travel_file_pretrip_email_schedule",travel_file_id:file.id,client_name:file.client_name,destination:file.destination,trip_type:file.trip_type,departure_date:file.departure_date,return_date:file.return_date,assigned_advisor_id:file.assigned_advisor_id,recipients,schedule};
try{const response=await fetch(webhookUrl,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload),cache:"no-store"});const responseText=await response.text();if(!response.ok){console.error("PRETRIP_EMAIL_SCHEDULE_WEBHOOK_FAILED",{status:response.status,response:responseText});return NextResponse.json({error:`Briitely schedule webhook returned ${response.status}.`},{status:502})}await c.db.from("travel_activity").insert({travel_file_id:travelFileId,event_type:"pretrip_email_schedule_synced",summary:`Pre-trip email schedule synced to Briitely for ${recipients.length} recipient${recipients.length===1?"":"s"}.`,actor_type:"internal",actor_user_id:c.user.id,metadata:{recipient_count:recipients.length,enabled_email_count:schedule.filter((e:any)=>e.enabled).length}});return NextResponse.json({success:true,recipientCount:recipients.length,enabledEmailCount:schedule.filter((e:any)=>e.enabled).length})}catch(e){console.error("PRETRIP_EMAIL_SCHEDULE_WEBHOOK_ERROR",e);return NextResponse.json({error:"Could not reach the Briitely pre-trip schedule webhook."},{status:502})}}
