import { NextResponse } from "next/server";
import { getAuthenticatedUser } from "@/lib/supabase/auth";
import { createClient } from "@/lib/supabase/server";
import { getContact, upsertContact } from "@/lib/briitely/contacts";

const PERMANENT_RELATIONSHIPS=new Set(["spouse_partner","child","adult_child","parent","other_family"]);
async function requireUser(){const{user,error}=await getAuthenticatedUser();return error||!user?null:user}
async function upsertContactTraveller(s:any,contactId:string){const contact=await getContact(contactId);const{data,error}=await s.from("traveller_profiles").upsert({briitely_contact_id:contact.id,first_name:contact.firstName||"Unknown",last_name:contact.lastName||"",email:contact.email||null,phone:contact.phone||null},{onConflict:"briitely_contact_id"}).select("id, briitely_contact_id, first_name, last_name, preferred_name, date_of_birth, email, phone").single();if(error||!data)throw new Error(error?.message??"Could not save traveller profile.");return data}
async function ensurePrimaryTraveller(s:any,travelFileId:string,contactId:string){const t=await upsertContactTraveller(s,contactId);const{error}=await s.from("travel_file_travellers").upsert({travel_file_id:travelFileId,traveller_profile_id:t.id,traveller_role:"primary",relationship_to_primary:"primary",receive_trip_communications:true,booking_form_required:false,booking_form_recipient_party_member_id:null},{onConflict:"travel_file_id,traveller_profile_id"});if(error)throw new Error(error.message)}
async function syncClientRelationship(s:any,primaryContactId:string|null,travellerProfileId:string,relationshipType:string|null){if(!primaryContactId||primaryContactId==="pending")return;if(relationshipType&&PERMANENT_RELATIONSHIPS.has(relationshipType)){const{error}=await s.from("client_relationships").upsert({primary_contact_id:primaryContactId,related_traveller_id:travellerProfileId,relationship_type:relationshipType},{onConflict:"primary_contact_id,related_traveller_id"});if(error)throw new Error(error.message);return}const{error}=await s.from("client_relationships").delete().eq("primary_contact_id",primaryContactId).eq("related_traveller_id",travellerProfileId);if(error)throw new Error(error.message)}
const partySelect=`id, traveller_role, relationship_to_primary, receive_trip_communications, booking_form_required, booking_form_recipient_party_member_id, booking_form_completed_at, traveller_profiles:traveller_profile_id (id, briitely_contact_id, first_name, last_name, preferred_name, date_of_birth, email, phone)`;

export async function GET(_req:Request,{params}:{params:Promise<{travelFileId:string}>}){if(!(await requireUser()))return NextResponse.json({error:"Unauthorized"},{status:401});const{travelFileId}=await params,s=await createClient();const{data:file,error}=await s.from("travel_files").select("id, briitely_contact_id, departure_date").eq("id",travelFileId).maybeSingle();if(error||!file)return NextResponse.json({error:"Travel File not found."},{status:404});try{if(file.briitely_contact_id&&file.briitely_contact_id!=="pending")await ensurePrimaryTraveller(s,travelFileId,file.briitely_contact_id);const[{data:party,error:pe},{data:submission}]=await Promise.all([s.from("travel_file_travellers").select(partySelect).eq("travel_file_id",travelFileId).order("created_at",{ascending:true}),s.from("booking_form_submissions").select("id, submitted_at, change_count").eq("travel_file_id",travelFileId).order("submitted_at",{ascending:false}).limit(1).maybeSingle()]);if(pe)throw new Error(pe.message);const{data:relationships,error:re}=file.briitely_contact_id?await s.from("client_relationships").select(`id, relationship_type, traveller_profiles:related_traveller_id (id, briitely_contact_id, first_name, last_name, preferred_name, date_of_birth, email, phone)`).eq("primary_contact_id",file.briitely_contact_id).order("created_at",{ascending:true}):{data:[],error:null};if(re)throw new Error(re.message);return NextResponse.json({party:party??[],relationships:relationships??[],departureDate:file.departure_date??null,completedBookingForm:submission??null})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Could not load travel party."},{status:500})}}

export async function POST(req:Request,{params}:{params:Promise<{travelFileId:string}>}){if(!(await requireUser()))return NextResponse.json({error:"Unauthorized"},{status:401});const{travelFileId}=await params,body=await req.json().catch(()=>null)as any;if(!body)return NextResponse.json({error:"Invalid request."},{status:400});const s=await createClient();try{const{data:file}=await s.from("travel_files").select("briitely_contact_id").eq("id",travelFileId).maybeSingle();if(!file)return NextResponse.json({error:"Travel File not found."},{status:404});let travellerId=body.travellerProfileId??null;if(body.existingCustomerId)travellerId=(await upsertContactTraveller(s,body.existingCustomerId)).id;if(!travellerId){const firstName=body.firstName?.trim(),lastName=body.lastName?.trim();if(!firstName||!lastName)return NextResponse.json({error:"First and last name are required."},{status:400});if(body.receiveTripCommunications&&!body.email?.trim())return NextResponse.json({error:"Email is required when a traveller receives trip communications."},{status:400});const{data,error}=await s.from("traveller_profiles").insert({first_name:firstName,last_name:lastName,preferred_name:body.preferredName?.trim()||null,date_of_birth:body.dateOfBirth||null,email:body.email?.trim()||null,phone:body.phone?.trim()||null}).select("id").single();if(error||!data)throw new Error(error?.message??"Could not create traveller.");travellerId=data.id}
 const{data:profile,error:profileError}=await s.from("traveller_profiles").select("email").eq("id",travellerId).maybeSingle();if(profileError||!profile)throw new Error(profileError?.message??"Traveller profile not found.");if(body.receiveTripCommunications&&!profile.email?.trim())return NextResponse.json({error:"Email is required when a traveller receives trip communications."},{status:400});
 const rel=body.relationshipToPrimary?.trim()||null;const{data,error}=await s.from("travel_file_travellers").upsert({travel_file_id:travelFileId,traveller_profile_id:travellerId,traveller_role:"traveller",relationship_to_primary:rel,receive_trip_communications:body.receiveTripCommunications??false,booking_form_required:false,booking_form_recipient_party_member_id:null},{onConflict:"travel_file_id,traveller_profile_id"}).select("id").single();if(error||!data)throw new Error(error?.message??"Could not add traveller to this trip.");await syncClientRelationship(s,file.briitely_contact_id,travellerId,rel);return NextResponse.json({traveller:data},{status:201})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Could not add traveller."},{status:500})}}

export async function PATCH(req:Request,{params}:{params:Promise<{travelFileId:string}>}){if(!(await requireUser()))return NextResponse.json({error:"Unauthorized"},{status:401});const{travelFileId}=await params,body=await req.json().catch(()=>null)as any;if(!body?.partyMemberId)return NextResponse.json({error:"Party member ID is required."},{status:400});const s=await createClient(),{data:m}=await s.from("travel_file_travellers").select("traveller_role, traveller_profile_id, relationship_to_primary, receive_trip_communications, booking_form_recipient_party_member_id").eq("id",body.partyMemberId).eq("travel_file_id",travelFileId).maybeSingle();if(!m)return NextResponse.json({error:"Traveller not found."},{status:404});const{data:p}=await s.from("traveller_profiles").select("id, briitely_contact_id, first_name, last_name, preferred_name, date_of_birth, email, phone").eq("id",m.traveller_profile_id).maybeSingle();if(!p)return NextResponse.json({error:"Traveller profile not found."},{status:404});try{
 const nextEmail=Object.prototype.hasOwnProperty.call(body,"email")?body.email?.trim()||null:p.email;const nextCommunications=typeof body.receiveTripCommunications==="boolean"?body.receiveTripCommunications:m.receive_trip_communications;if(nextCommunications&&!nextEmail)return NextResponse.json({error:"Email is required when a traveller receives trip communications."},{status:400});
 if(Object.prototype.hasOwnProperty.call(body,"bookingFormRecipientPartyMemberId")){if(m.traveller_role==="primary"&&body.bookingFormRecipientPartyMemberId)return NextResponse.json({error:"The primary traveller must stay on the primary booking form."},{status:400});const recipientId=body.bookingFormRecipientPartyMemberId||null;if(recipientId){const{data:r}=await s.from("travel_file_travellers").select("id,traveller_profiles:traveller_profile_id(email)").eq("id",recipientId).eq("travel_file_id",travelFileId).maybeSingle();const rp=Array.isArray(r?.traveller_profiles)?r?.traveller_profiles[0]:r?.traveller_profiles;if(!r)return NextResponse.json({error:"Booking form recipient must be a traveller on this trip."},{status:400});if(!rp?.email?.trim())return NextResponse.json({error:"The booking form recipient needs an email address before they can receive a form."},{status:400});}}
 const u:any={};if(typeof body.relationshipToPrimary==="string"&&m.traveller_role!=="primary")u.relationship_to_primary=body.relationshipToPrimary.trim()||null;if(typeof body.receiveTripCommunications==="boolean")u.receive_trip_communications=body.receiveTripCommunications;if(Object.prototype.hasOwnProperty.call(body,"bookingFormRecipientPartyMemberId")&&m.traveller_role!=="primary"){u.booking_form_recipient_party_member_id=body.bookingFormRecipientPartyMemberId||null;u.booking_form_required=Boolean(body.bookingFormRecipientPartyMemberId)}if(Object.keys(u).length){const{error}=await s.from("travel_file_travellers").update(u).eq("id",body.partyMemberId);if(error)throw new Error(error.message)}
 const has=["firstName","lastName","preferredName","dateOfBirth","email","phone"].some(k=>Object.prototype.hasOwnProperty.call(body,k));let clientId=p.briitely_contact_id;if(has){const firstName=body.firstName?.trim()||p.first_name,lastName=body.lastName?.trim()||p.last_name;const{error}=await s.from("traveller_profiles").update({first_name:firstName,last_name:lastName,preferred_name:Object.prototype.hasOwnProperty.call(body,"preferredName")?body.preferredName?.trim()||null:p.preferred_name,date_of_birth:Object.prototype.hasOwnProperty.call(body,"dateOfBirth")?body.dateOfBirth||null:p.date_of_birth,email:nextEmail,phone:Object.prototype.hasOwnProperty.call(body,"phone")?body.phone?.trim()||null:p.phone}).eq("id",p.id);if(error)throw new Error(error.message)}
 if(body.createClientFile&&!clientId){const r=await upsertContact({firstName:body.firstName?.trim()||p.first_name,lastName:body.lastName?.trim()||p.last_name,email:nextEmail||undefined,phone:body.phone?.trim()||p.phone||undefined});clientId=r.customer.id;await s.from("traveller_profiles").update({briitely_contact_id:clientId}).eq("id",p.id)}if(m.traveller_role!=="primary"&&typeof body.relationshipToPrimary==="string"){const{data:f}=await s.from("travel_files").select("briitely_contact_id").eq("id",travelFileId).maybeSingle();await syncClientRelationship(s,f?.briitely_contact_id??null,m.traveller_profile_id,body.relationshipToPrimary.trim()||null)}return NextResponse.json({updated:true,clientId})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Could not update traveller."},{status:500})}}

export async function DELETE(req:Request,{params}:{params:Promise<{travelFileId:string}>}){if(!(await requireUser()))return NextResponse.json({error:"Unauthorized"},{status:401});const{travelFileId}=await params,id=new URL(req.url).searchParams.get("partyMemberId");if(!id)return NextResponse.json({error:"Party member ID is required."},{status:400});const s=await createClient(),{data:m}=await s.from("travel_file_travellers").select("traveller_role").eq("id",id).eq("travel_file_id",travelFileId).maybeSingle();if(m?.traveller_role==="primary")return NextResponse.json({error:"The primary client cannot be removed from the travel party."},{status:400});await s.from("travel_file_travellers").update({booking_form_recipient_party_member_id:null,booking_form_required:false}).eq("travel_file_id",travelFileId).eq("booking_form_recipient_party_member_id",id);const{error}=await s.from("travel_file_travellers").delete().eq("id",id).eq("travel_file_id",travelFileId);if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({deleted:true})}
