"use client";

import { useEffect, useState, type FormEvent } from "react";
import { Loader2, X } from "lucide-react";
import { Button } from "@/components/core/ui/button";
import { Input } from "@/components/core/ui/input";
import { Label } from "@/components/core/ui/label";
import type { BriitelyCustomer } from "@/lib/briitely/types";
import { budgetRangeOptions, tripTypeOptions } from "@/lib/travel/tag-mappings";

interface AdvisorOption { id:string; full_name:string; ghl_user_id?:string|null }
interface CreateTravelFileModalProps { customer:BriitelyCustomer; advisors:AdvisorOption[]; open:boolean; onOpenChange:(open:boolean)=>void; onCreated:(travelFileId:string)=>void }
const INQUIRY_SOURCES=[{value:"web",label:"Web"},{value:"email",label:"Email"},{value:"phone",label:"Phone"},{value:"referral",label:"Referral"},{value:"repeat_client",label:"Repeat Client"},{value:"other",label:"Other"}];

export function CreateTravelFileModal({customer,advisors,open,onOpenChange,onCreated}:CreateTravelFileModalProps){
 const[inquirySource,setInquirySource]=useState("");const[destination,setDestination]=useState("");const[tripType,setTripType]=useState("");const[departureDate,setDepartureDate]=useState("");const[returnDate,setReturnDate]=useState("");const[numberOfAdults,setNumberOfAdults]=useState("1");const[numberOfChildren,setNumberOfChildren]=useState("");const[budgetRange,setBudgetRange]=useState("");const[assignedAdvisorId,setAssignedAdvisorId]=useState("");const[notes,setNotes]=useState("");const[saving,setSaving]=useState(false);const[error,setError]=useState<string|null>(null);
 useEffect(()=>{if(!open)return;const match=customer.assignedUserId?advisors.find(a=>a.ghl_user_id===customer.assignedUserId):undefined;setAssignedAdvisorId(match?.id??"")},[open,customer.assignedUserId,advisors]);
 if(!open)return null;
 async function handleSubmit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError(null);if(!inquirySource){setError("Please select an inquiry source.");return}const adults=parseInt(numberOfAdults,10)||0,children=numberOfChildren?parseInt(numberOfChildren,10):0;if(adults<1){setError("At least one adult is required.");return}if(children<0){setError("Number of children cannot be negative.");return}if(departureDate&&returnDate&&new Date(returnDate)<new Date(departureDate)){setError("Return date cannot be before departure date.");return}setSaving(true);try{const body:Record<string,unknown>={briitelyContactId:customer.id,clientName:customer.name||[customer.firstName,customer.lastName].filter(Boolean).join(" "),inquirySource,numberOfAdults:adults,numberOfChildren:children,numberOfTravellers:adults+children};if(destination.trim())body.destination=destination.trim();if(tripType)body.tripType=tripType;if(departureDate)body.departureDate=departureDate;if(returnDate)body.returnDate=returnDate;if(budgetRange)body.budgetRange=budgetRange;if(assignedAdvisorId)body.assignedAdvisorId=assignedAdvisorId;if(notes.trim())body.notes=notes.trim();const res=await fetch("/api/travel-files/create",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await res.json();if(!res.ok){setError(data.error||"Failed to create Travel File.");return}onCreated(data.travelFileId);onOpenChange(false)}catch{setError("Something went wrong creating the Travel File.")}finally{setSaving(false)}}
 return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4" role="presentation"><div className="max-h-[min(760px,calc(100vh-2rem))] w-full max-w-2xl overflow-y-auto rounded-xl border bg-background shadow-xl" role="dialog" aria-modal="true"><div className="flex items-center justify-between border-b px-6 py-4"><div><h2 className="text-xl font-semibold">Create Travel File</h2><p className="mt-1 text-sm text-muted-foreground">for {customer.name||[customer.firstName,customer.lastName].filter(Boolean).join(" ")||customer.companyName||"Customer"}</p></div><Button type="button" variant="ghost" size="icon" onClick={()=>onOpenChange(false)} disabled={saving}><X className="h-5 w-5"/></Button></div><form onSubmit={handleSubmit} className="space-y-5 p-6">
 <div className="space-y-2"><Label>Inquiry Source *</Label><select value={inquirySource} onChange={e=>setInquirySource(e.target.value)} required className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"><option value="">Select source...</option>{INQUIRY_SOURCES.map(s=><option key={s.value} value={s.value}>{s.label}</option>)}</select></div>
 <div className="space-y-2"><Label>Destination</Label><Input value={destination} onChange={e=>setDestination(e.target.value)} placeholder="e.g. Mexico, Caribbean Cruise"/></div>
 <div className="space-y-2"><Label>Trip Type</Label><select value={tripType} onChange={e=>setTripType(e.target.value)} className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"><option value="">Select type...</option>{tripTypeOptions.map(t=><option key={t} value={t}>{t}</option>)}</select></div>
 <div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label>Adults *</Label><Input type="number" min="1" value={numberOfAdults} onChange={e=>setNumberOfAdults(e.target.value)} required/></div><div className="space-y-2"><Label>Children</Label><Input type="number" min="0" value={numberOfChildren} onChange={e=>setNumberOfChildren(e.target.value)}/></div></div>
 <div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label>Departure Date</Label><Input type="date" value={departureDate} onChange={e=>setDepartureDate(e.target.value)}/></div><div className="space-y-2"><Label>Return Date</Label><Input type="date" value={returnDate} onChange={e=>setReturnDate(e.target.value)}/></div></div>
 <div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label>Budget per Person</Label><select value={budgetRange} onChange={e=>setBudgetRange(e.target.value)} className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"><option value="">Select...</option>{budgetRangeOptions.map(opt=><option key={opt} value={opt}>{opt}</option>)}</select></div><div className="space-y-2"><Label>Assigned Advisor</Label><select value={assignedAdvisorId} onChange={e=>setAssignedAdvisorId(e.target.value)} className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"><option value="">Unassigned</option>{advisors.map(a=><option key={a.id} value={a.id}>{a.full_name}</option>)}</select>{customer.assignedUserId&&!assignedAdvisorId&&<p className="text-xs text-muted-foreground">The Briitely assigned user is not linked to an active portal advisor.</p>}</div></div>
 <div className="space-y-2"><Label>Notes</Label><textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={3} placeholder="Any additional context about this inquiry..." className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm"/></div>{error&&<p className="text-sm text-destructive">{error}</p>}<div className="flex justify-end gap-3 border-t pt-5"><Button type="button" variant="outline" onClick={()=>onOpenChange(false)} disabled={saving}>Cancel</Button><Button type="submit" disabled={saving}>{saving?<><Loader2 className="h-4 w-4 animate-spin"/>Creating...</>:"Create Travel File"}</Button></div></form></div></div>
}
