"use client";
import {useState} from "react";
import {ClipboardCheck} from "lucide-react";
import {Button} from "@/components/core/ui/button";
import {CompleteConsultationModal} from "@/components/app/complete-consultation-modal";
import {SendTmfButton} from "@/components/app/send-tmf-button";

type Props={travelFileId:string;clientName:string;destination:string|null;tripType:string|null;travelTimeframe:string|null;departureDate:string|null;returnDate:string|null;numberOfAdults:number|null;numberOfChildren:number|null;childrenAges:string|null;budgetRange:string|null;insuranceInterest:string|null;specialConsiderations:string|null;staffNotes:string|null;assignedAdvisorId:string|null;currentActionCode:string|null;currentActionStatus:string|null;canEdit:boolean;canSendRetainer:boolean;email:string;phone:string;assignedAdvisorName:string|null;agreementType:string|null;tmfAmount:number|null;revisionsIncluded:number|null;previousNotes:Array<{id:string;note_type:string;note_text:string;created_at:string;author:{id:string;full_name:string}|null}>};
export function CurrentActionPrimaryButton(p:Props){const[open,setOpen]=useState(false);if(!p.canEdit||p.currentActionStatus!=="active")return null;if(p.currentActionCode==="complete_initial_consultation")return <><Button size="sm" onClick={()=>setOpen(true)}><ClipboardCheck className="h-4 w-4"/>Complete Initial Consultation</Button>{open&&<CompleteConsultationModal key={`consult-${p.travelFileId}-${open}`} travelFileId={p.travelFileId} clientName={p.clientName} destination={p.destination} tripType={p.tripType} travelTimeframe={p.travelTimeframe} departureDate={p.departureDate} returnDate={p.returnDate} numberOfAdults={p.numberOfAdults} numberOfChildren={p.numberOfChildren} childrenAges={p.childrenAges} budgetRange={p.budgetRange} specialConsiderations={p.specialConsiderations} insuranceInterest={p.insuranceInterest} assignedAdvisorId={p.assignedAdvisorId} staffNotes={p.staffNotes} previousNotes={p.previousNotes} isOpen={open} onClose={()=>setOpen(false)}/>}</>;if(p.currentActionCode==="send_tmf_agreement"&&p.canSendRetainer)return <SendTmfButton travelFileId={p.travelFileId} clientName={p.clientName} email={p.email} phone={p.phone} destination={p.destination} assignedAdvisorName={p.assignedAdvisorName} agreementType={p.agreementType} tmfAmount={p.tmfAmount} revisionsIncluded={p.revisionsIncluded} agreementDate={new Date().toLocaleDateString("en-CA")}/>;return null}
