"use client";
import {useState} from "react";
import {useRouter} from "next/navigation";
import {CalendarClock,MessageSquareText,X,Loader2} from "lucide-react";
import {Button} from "@/components/core/ui/button";
import {Input} from "@/components/core/ui/input";
import {Label} from "@/components/core/ui/label";

export function CurrentActionControls({travelFileId,dueAt,notes}:{travelFileId:string;dueAt:string|null;notes:string|null}){
 const router=useRouter();const[mode,setMode]=useState<"due"|"note"|null>(null);const[due,setDue]=useState(dueAt?dueAt.slice(0,10):"");const[note,setNote]=useState(notes??"");const[saving,setSaving]=useState(false);const[error,setError]=useState<string|null>(null);
 async function save(){setSaving(true);setError(null);try{const body=mode==="due"?{dueAt:due?`${due}T17:00:00`:null}:{notes:note||null};const r=await fetch(`/api/travel-files/${encodeURIComponent(travelFileId)}/current-action`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error??"Could not update action.");setMode(null);router.refresh()}catch(e){setError(e instanceof Error?e.message:"Could not update action.")}finally{setSaving(false)}}
 return <><div className="mt-3 flex w-full flex-col gap-2"><Button variant="outline" size="sm" className="justify-start" onClick={()=>setMode("due")}><CalendarClock className="h-4 w-4"/>Set / Adjust Due Date</Button><Button variant="outline" size="sm" className="justify-start" onClick={()=>setMode("note")}><MessageSquareText className="h-4 w-4"/>{notes?"Edit Action Note":"Add Action Note"}</Button></div>{mode&&<div className="fixed inset-0 z-50 flex items-start justify-center bg-black/50 p-4 pt-24"><div className="w-full max-w-md rounded-xl bg-background p-5 shadow-xl"><div className="flex items-start justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[.12em] text-primary">Current Action</p><h2 className="mt-1 text-lg font-semibold">{mode==="due"?"Set / Adjust Due Date":"Action Note"}</h2></div><Button variant="ghost" size="sm" onClick={()=>setMode(null)}><X className="h-4 w-4"/></Button></div><div className="mt-5 space-y-4">{mode==="due"?<div className="space-y-2"><Label>Due date</Label><Input type="date" value={due} onChange={e=>setDue(e.target.value)}/><p className="text-xs text-muted-foreground">Clear the date to return this action to a waiting state.</p></div>:<div className="space-y-2"><Label>Operational note</Label><textarea className="min-h-28 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" value={note} onChange={e=>setNote(e.target.value)} placeholder="Example: Client asked us to follow up again in 10 days."/><p className="text-xs text-muted-foreground">This stays with this action for workflow context. Permanent client or trip information belongs in Notes.</p></div>}{error&&<p className="text-sm text-destructive">{error}</p>}<div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>setMode(null)} disabled={saving}>Cancel</Button><Button onClick={save} disabled={saving}>{saving&&<Loader2 className="h-4 w-4 animate-spin"/>}Save</Button></div></div></div></div>}</>
}
