"use client";

import { useEffect, useState } from "react";
import { Loader2, Pencil } from "lucide-react";
import { Button } from "@/components/core/ui/button";
import { Input } from "@/components/core/ui/input";
import { Label } from "@/components/core/ui/label";
import { travelInterestOptions, travelSeasonOptions } from "@/lib/travel/tag-mappings";

interface TravelProfile { travel_interests:string[]; travel_seasons:string[]; last_travel_destination:string|null; last_travel_date:string|null }
const EMPTY_PROFILE:TravelProfile={travel_interests:[],travel_seasons:[],last_travel_destination:null,last_travel_date:null};

export function CustomerTravelProfileCard({customerId}:{customerId:string}){
 const[profile,setProfile]=useState<TravelProfile>(EMPTY_PROFILE);const[draft,setDraft]=useState<TravelProfile>(EMPTY_PROFILE);const[loading,setLoading]=useState(true);const[editing,setEditing]=useState(false);const[saving,setSaving]=useState(false);const[error,setError]=useState<string|null>(null);
 useEffect(()=>{let active=true;setLoading(true);fetch(`/api/customers/${encodeURIComponent(customerId)}/travel-profile`).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error??"Could not load travel profile.");if(active){const n=d.profile??EMPTY_PROFILE;setProfile(n);setDraft(n)}}).catch(e=>{if(active)setError(e instanceof Error?e.message:"Could not load travel profile.")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[customerId]);
 function toggleList(key:"travel_interests"|"travel_seasons",value:string){setDraft(c=>({...c,[key]:c[key].includes(value)?c[key].filter(x=>x!==value):[...c[key],value]}))}
 async function save(){setSaving(true);setError(null);try{const r=await fetch(`/api/customers/${encodeURIComponent(customerId)}/travel-profile`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({travelInterests:draft.travel_interests,travelSeasons:draft.travel_seasons,lastTravelDestination:draft.last_travel_destination,lastTravelDate:draft.last_travel_date})});const d=await r.json();if(!r.ok)throw new Error(d.error??"Could not save travel profile.");setProfile(d.profile);setDraft(d.profile);setEditing(false)}catch(e){setError(e instanceof Error?e.message:"Could not save travel profile.")}finally{setSaving(false)}}
 return <div className="rounded-xl border bg-[#fffefa] p-5 shadow-sm"><div className="grid gap-5 md:grid-cols-[220px_minmax(0,1fr)]"><div className="flex flex-col items-start"><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-primary">Travel</p><h2 className="mt-1 font-serif text-xl leading-tight">Travel profile</h2><p className="mt-2 text-xs leading-relaxed text-muted-foreground">Persistent preferences used across this client&apos;s trips.</p>{!editing&&!loading&&<Button variant="outline" size="sm" onClick={()=>{setDraft(profile);setEditing(true)}} className="mt-3 justify-start"><Pencil className="h-4 w-4"/>Edit Travel Profile</Button>}</div><div>{loading?<p className="flex items-center gap-2 text-sm text-muted-foreground"><Loader2 className="h-4 w-4 animate-spin"/>Loading travel profile...</p>:editing?<div className="space-y-5"><OptionGroup title="Travel Interests" options={travelInterestOptions.map(o=>o.label)} selected={draft.travel_interests} onToggle={v=>toggleList("travel_interests",v)}/><OptionGroup title="Preferred Travel Seasons" options={travelSeasonOptions.map(o=>o.label)} selected={draft.travel_seasons} onToggle={v=>toggleList("travel_seasons",v)} compact/><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label>Last Travel Destination</Label><Input value={draft.last_travel_destination??""} onChange={e=>setDraft({...draft,last_travel_destination:e.target.value||null})}/></div><div className="space-y-2"><Label>Last Travel Date</Label><Input type="date" value={draft.last_travel_date??""} onChange={e=>setDraft({...draft,last_travel_date:e.target.value||null})}/></div></div>{error&&<p className="text-sm text-destructive">{error}</p>}<div className="flex gap-3"><Button onClick={save} disabled={saving}>{saving&&<Loader2 className="h-4 w-4 animate-spin"/>}{saving?"Saving...":"Save Travel Profile"}</Button><Button variant="outline" onClick={()=>{setDraft(profile);setEditing(false);setError(null)}} disabled={saving}>Cancel</Button></div></div>:<><h3 className="mb-3 border-b pb-2 text-xs font-semibold uppercase tracking-wide text-muted-foreground">Preferences</h3><div className="space-y-5"><ProfileList label="Travel Interests" values={profile.travel_interests}/><ProfileList label="Preferred Travel Seasons" values={profile.travel_seasons}/><div className="grid gap-4 sm:grid-cols-2"><ProfileValue label="Last Travel Destination" value={profile.last_travel_destination}/><ProfileValue label="Last Travel Date" value={profile.last_travel_date}/></div>{error&&<p className="text-sm text-destructive">{error}</p>}</div></>}</div></div></div>
}
function OptionGroup({title,options,selected,onToggle,compact=false}:{title:string;options:string[];selected:string[];onToggle:(v:string)=>void;compact?:boolean}){return <div className="space-y-2"><Label>{title}</Label><div className={`grid gap-2 ${compact?"sm:grid-cols-5":"sm:grid-cols-3"}`}>{options.map(o=><label key={o} className="flex items-center gap-2 rounded-md border px-3 py-2 text-sm"><input type="checkbox" checked={selected.includes(o)} onChange={()=>onToggle(o)}/>{o}</label>)}</div></div>}
function ProfileList({label,values}:{label:string;values:string[]}){return <div><p className="text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">{label}</p>{values.length?<div className="mt-2 flex flex-wrap gap-2">{values.map(v=><span key={v} className="rounded-full bg-muted px-3 py-1 text-sm">{v}</span>)}</div>:<p className="mt-1 text-sm text-muted-foreground">Not provided</p>}</div>}
function ProfileValue({label,value}:{label:string;value:string|null}){return <div><p className="text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 text-sm font-medium">{value||"Not provided"}</p></div>}
