"use client";

import { useEffect, useState } from "react";
import { CheckCircle2, Loader2, Plane, ShieldCheck } from "lucide-react";
import { Button } from "@/components/core/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/core/ui/card";
import { Input } from "@/components/core/ui/input";
import { Label } from "@/components/core/ui/label";

type Profile = {
  id: string; first_name: string; middle_name: string|null; last_name: string; preferred_name: string|null;
  date_of_birth: string|null; email: string|null; phone: string|null; passport_number: string|null;
  passport_country: string|null; passport_issue_date: string|null; passport_expiry_date: string|null;
  emergency_contact_name: string|null; emergency_contact_relationship: string|null; emergency_contact_phone: string|null; emergency_contact_email: string|null;
};
type Member = { id:string; traveller_role:string; relationship_to_primary:string|null; traveller_profiles:Profile|Profile[] };
type FormTraveller = { id:string; firstName:string; middleName:string; lastName:string; preferredName:string; dateOfBirth:string; email:string; phone:string; passportNumber:string; passportCountry:string; passportIssueDate:string; passportExpiryDate:string; emergencyContactName:string; emergencyContactRelationship:string; emergencyContactPhone:string; emergencyContactEmail:string };
type Trip = { client_name:string; destination:string|null; departure_date:string|null; return_date:string|null };
const relationshipLabels:Record<string,string>={primary:"Primary Traveller",spouse_partner:"Spouse / Partner",child:"Child",parent:"Parent",other_family:"Family Member",household:"Household Member",friend:"Friend",travel_companion:"Travel Companion"};
const val=(value:string|null|undefined)=>value??"";
function profileOf(member:Member){return Array.isArray(member.traveller_profiles)?member.traveller_profiles[0]:member.traveller_profiles}
function toForm(profile:Profile):FormTraveller{return{id:profile.id,firstName:val(profile.first_name),middleName:val(profile.middle_name),lastName:val(profile.last_name),preferredName:val(profile.preferred_name),dateOfBirth:val(profile.date_of_birth),email:val(profile.email),phone:val(profile.phone),passportNumber:val(profile.passport_number),passportCountry:val(profile.passport_country),passportIssueDate:val(profile.passport_issue_date),passportExpiryDate:val(profile.passport_expiry_date),emergencyContactName:val(profile.emergency_contact_name),emergencyContactRelationship:val(profile.emergency_contact_relationship),emergencyContactPhone:val(profile.emergency_contact_phone),emergencyContactEmail:val(profile.emergency_contact_email)}}
function dateText(value:string|null){if(!value)return null;return new Date(`${value}T00:00:00`).toLocaleDateString("en-CA",{year:"numeric",month:"long",day:"numeric"})}
async function readResponse(response:Response){const text=await response.text();if(!text)return{} as Record<string,unknown>;try{return JSON.parse(text) as Record<string,unknown>}catch{return{error:response.ok?"The server returned an invalid response.":`Booking form request failed (${response.status}).`}}}

export function CustomerBookingForm({token}:{token:string}){
 const[trip,setTrip]=useState<Trip|null>(null);const[members,setMembers]=useState<Member[]>([]);const[travellers,setTravellers]=useState<FormTraveller[]>([]);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[submitted,setSubmitted]=useState(false);const[error,setError]=useState<string|null>(null);const[confirmed,setConfirmed]=useState(false);
 useEffect(()=>{(async()=>{try{const response=await fetch(`/api/booking/${encodeURIComponent(token)}`);const data=await readResponse(response);if(!response.ok)throw new Error(typeof data.error==="string"?data.error:"Could not load booking form.");setTrip(data.trip as Trip);const loadedMembers=(data.travellers??[]) as Member[];setMembers(loadedMembers);setTravellers(loadedMembers.map(member=>toForm(profileOf(member))));setSubmitted(Boolean(data.completed))}catch(err){setError(err instanceof Error?err.message:"Could not load booking form.")}finally{setLoading(false)}})()},[token]);
 function update(index:number,key:keyof FormTraveller,value:string){setTravellers(current=>current.map((traveller,i)=>i===index?{...traveller,[key]:value}:traveller))}
 async function submit(){if(!confirmed)return setError("Please confirm the information is accurate before submitting.");setSaving(true);setError(null);try{const response=await fetch(`/api/booking/${encodeURIComponent(token)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({travellers})});const data=await readResponse(response);if(!response.ok)throw new Error(typeof data.error==="string"?data.error:"Could not submit booking form.");setSubmitted(true);window.scrollTo({top:0,behavior:"smooth"})}catch(err){setError(err instanceof Error?err.message:"Could not submit booking form.")}finally{setSaving(false)}}
 if(loading)return <div className="py-20 text-center text-muted-foreground"><Loader2 className="mx-auto mb-3 h-6 w-6 animate-spin"/>Loading your booking form...</div>;
 if(error&&!trip)return <Card><CardContent className="py-12 text-center"><p className="font-medium text-destructive">{error}</p><p className="mt-2 text-sm text-muted-foreground">Please contact Inspired Vacations for a new booking form link.</p></CardContent></Card>;
 if(submitted)return <Card className="border-primary/20 shadow-lg"><CardContent className="py-14 text-center"><CheckCircle2 className="mx-auto h-12 w-12 text-green-600"/><h2 className="mt-4 text-2xl font-semibold">Thank you!</h2><p className="mx-auto mt-2 max-w-xl text-muted-foreground">Your traveller information has been securely submitted to Inspired Vacations. Your travel advisor will use these details to prepare your booking.</p></CardContent></Card>;
 return <div className="space-y-6">
  <Card className="overflow-hidden border-primary/20 shadow-md"><CardContent className="p-6 sm:p-8"><div className="flex items-start gap-4"><div className="rounded-full bg-primary/10 p-3"><Plane className="h-6 w-6 text-primary"/></div><div><p className="text-sm font-medium text-primary">Your upcoming trip</p><h2 className="mt-1 text-2xl font-semibold">{trip?.destination||"Your Inspired Vacation"}</h2><p className="mt-1 text-muted-foreground">{trip?.departure_date?dateText(trip.departure_date):"Travel dates to be confirmed"}{trip?.return_date?` – ${dateText(trip.return_date)}`:""}</p></div></div></CardContent></Card>
  <div className="rounded-lg border border-border bg-muted/30 p-4 text-sm text-muted-foreground"><div className="flex gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-primary"/><p>Please enter each traveller&apos;s information exactly as it appears on their passport or government-issued travel document. This form does not collect payment or credit-card information.</p></div></div>
  {travellers.map((traveller,index)=>{const member=members[index];return <Card key={traveller.id}><CardHeader><CardTitle>{traveller.preferredName||traveller.firstName||`Traveller ${index+1}`} <span className="ml-2 text-sm font-normal text-muted-foreground">{relationshipLabels[member?.relationship_to_primary??""]??(member?.traveller_role==="primary"?"Primary Traveller":"Traveller")}</span></CardTitle></CardHeader><CardContent className="space-y-6">
   <Section title="Legal name & contact"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Field label="Legal First Name *"><Input value={traveller.firstName} onChange={e=>update(index,"firstName",e.target.value)}/></Field><Field label="Middle Name"><Input value={traveller.middleName} onChange={e=>update(index,"middleName",e.target.value)}/></Field><Field label="Legal Last Name *"><Input value={traveller.lastName} onChange={e=>update(index,"lastName",e.target.value)}/></Field><Field label="Preferred Name"><Input value={traveller.preferredName} onChange={e=>update(index,"preferredName",e.target.value)}/></Field><Field label="Date of Birth *"><Input type="date" value={traveller.dateOfBirth} onChange={e=>update(index,"dateOfBirth",e.target.value)}/></Field><Field label="Email"><Input type="email" value={traveller.email} onChange={e=>update(index,"email",e.target.value)}/></Field><Field label="Phone"><Input type="tel" value={traveller.phone} onChange={e=>update(index,"phone",e.target.value)}/></Field></div></Section>
   <Section title="Passport / travel document"><p className="mb-4 text-sm text-muted-foreground">If a passport is required for this trip, enter the details below exactly as shown on the document.</p><div className="grid gap-4 sm:grid-cols-2"><Field label="Passport Number"><Input value={traveller.passportNumber} onChange={e=>update(index,"passportNumber",e.target.value)}/></Field><Field label="Issuing Country"><Input value={traveller.passportCountry} onChange={e=>update(index,"passportCountry",e.target.value)} placeholder="e.g. Canada"/></Field><Field label="Issue Date"><Input type="date" value={traveller.passportIssueDate} onChange={e=>update(index,"passportIssueDate",e.target.value)}/></Field><Field label="Expiry Date"><Input type="date" value={traveller.passportExpiryDate} onChange={e=>update(index,"passportExpiryDate",e.target.value)}/></Field></div></Section>
   <Section title="Emergency contact"><div className="grid gap-4 sm:grid-cols-2"><Field label="Name"><Input value={traveller.emergencyContactName} onChange={e=>update(index,"emergencyContactName",e.target.value)}/></Field><Field label="Relationship"><Input value={traveller.emergencyContactRelationship} onChange={e=>update(index,"emergencyContactRelationship",e.target.value)}/></Field><Field label="Phone"><Input type="tel" value={traveller.emergencyContactPhone} onChange={e=>update(index,"emergencyContactPhone",e.target.value)}/></Field><Field label="Email"><Input type="email" value={traveller.emergencyContactEmail} onChange={e=>update(index,"emergencyContactEmail",e.target.value)}/></Field></div></Section>
  </CardContent></Card>})}
  <Card><CardContent className="space-y-5 p-6"><label className="flex cursor-pointer items-start gap-3"><input className="mt-1 h-4 w-4" type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span className="text-sm">I have reviewed the traveller information above and confirm that names, dates of birth, and travel-document details are accurate.</span></label>{error&&<p className="text-sm text-destructive">{error}</p>}<div className="flex justify-end"><Button size="lg" onClick={submit} disabled={saving}>{saving?<Loader2 className="h-4 w-4 animate-spin"/>:<CheckCircle2 className="h-4 w-4"/>}{saving?"Submitting...":"Submit Booking Information"}</Button></div></CardContent></Card>
 </div>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-2"><Label>{label}</Label>{children}</div>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section><h3 className="mb-4 border-b border-border pb-2 font-semibold">{title}</h3>{children}</section>}
