"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { Bold, ChevronDown, ChevronRight, Eye, Italic, Link as LinkIcon, List, Loader2, Save, Variable } from "lucide-react";
import { Button } from "@/components/core/ui/button";
import { Input } from "@/components/core/ui/input";
import { Label } from "@/components/core/ui/label";

type Template={email_code:string;email_name:string;subject:string;body_html:string};
const timing:Record<string,string>={proposal_initial:"Sent when the initial proposal is ready",proposal_resend:"Used when resending a proposal",retainer_booking_form:"Initial retainer agreement and primary booking form",primary_booking_form_reminder:"Used whenever a booking form needs to be sent again",additional_traveller_booking_form:"Separate booking form for an additional traveller",trip_plans_sent:"When TripPlans itinerary is sent",insurance:"1 day after TripPlans is sent",seat_selection:"1 week after TripPlans is sent",vaccines_visas:"180 days before departure",destination_spending:"75 days before departure",pre_trip_pamper:"60 days before departure",staying_connected:"45 days before departure",final_countdown:"30 days before departure",luggage_packing:"14 days before departure",almost_time:"2 days before departure",welcome_home:"3 days after return"};
const variables=[["First Name","{{first_name}}"],["Destination","{{destination}}"],["Departure Date","{{departure_date}}"],["Return Date","{{return_date}}"],["Advisor First Name","{{advisor_first_name}}"],["Primary First Name","{{primary_first_name}}"]] as const;
const clientOrder=["retainer_booking_form","primary_booking_form_reminder","additional_traveller_booking_form","proposal_initial","proposal_resend"];
const scheduledOrder=["trip_plans_sent","insurance","seat_selection","vaccines_visas","destination_spending","pre_trip_pamper","staying_connected","final_countdown","luggage_packing","almost_time","welcome_home"];
const clientCodes=new Set(clientOrder);
const orderBy=(order:string[])=>(a:Template,b:Template)=>{const ai=order.indexOf(a.email_code),bi=order.indexOf(b.email_code);return(ai<0?999:ai)-(bi<0?999:bi)};

function renderPreview(html:string){
  return html.replaceAll("{{first_name}}","Lana").replaceAll("{{destination}}","Malaga, Spain").replaceAll("{{departure_date}}","April 18, 2027").replaceAll("{{return_date}}","May 7, 2027").replaceAll("{{travefy_trip_plan_url}}","#").replace(/<a href="#">View Itinerary<\/a>/g,'<a href="#" style="display:inline-block;background:#e2735a;color:#fff;text-decoration:none;font-weight:600;padding:12px 28px;border-radius:5px;">View Itinerary</a>');
}

export function EmailTemplateEditor(){
 const[templates,setTemplates]=useState<Template[]>([]),[code,setCode]=useState("trip_plans_sent"),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(""),[preview,setPreview]=useState(false),[clientOpen,setClientOpen]=useState(true),[scheduledOpen,setScheduledOpen]=useState(true);
 const editor=useRef<HTMLDivElement>(null);
 useEffect(()=>{fetch("/api/admin/email-templates",{cache:"no-store"}).then(r=>r.json()).then(d=>setTemplates(d.templates??[])).finally(()=>setLoading(false))},[]);
 const current=useMemo(()=>templates.find(t=>t.email_code===code),[templates,code]);
 useEffect(()=>{if(!preview&&editor.current&&current)editor.current.innerHTML=current.body_html},[code,current?.email_code,preview]);
 function patch(change:Partial<Template>){setTemplates(v=>v.map(t=>t.email_code===code?{...t,...change}:t));setMessage("")}
 function sync(){if(editor.current)patch({body_html:editor.current.innerHTML})}
 function command(name:string,value?:string){editor.current?.focus();document.execCommand(name,false,value);sync()} function toggleBullets(){editor.current?.focus();const selection=window.getSelection();if(selection&&selection.rangeCount&&selection.isCollapsed){document.execCommand("insertText",false,"• ");}else{document.execCommand("insertUnorderedList",false);}sync()}
 function insert(text:string){editor.current?.focus();document.execCommand("insertText",false,text);sync()}
 function addLink(){const url=window.prompt("Paste the link URL");if(url)command("createLink",url)}
 function insertItinerary(){editor.current?.focus();document.execCommand("insertHTML",false,'<p><a href="{{travefy_trip_plan_url}}" style="display:inline-block;background:#e2735a;color:#fff;text-decoration:none;font-weight:600;padding:12px 28px;border-radius:5px;">View Itinerary</a></p>');sync()}
 async function save(){if(!current)return;sync();const latest={...current,body_html:editor.current?.innerHTML??current.body_html};setSaving(true);setMessage("");const r=await fetch("/api/admin/email-templates",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(latest)});const d=await r.json().catch(()=>({}));setMessage(r.ok?"Saved.":d.error??"Could not save template.");setSaving(false)}
 if(loading)return <div className="flex items-center gap-2 text-sm text-muted-foreground"><Loader2 className="h-4 w-4 animate-spin"/>Loading templates...</div>;
 return <div className="grid gap-6 lg:grid-cols-[260px_minmax(0,1fr)]">
  <aside className="space-y-5"><div><button type="button" onClick={()=>setClientOpen(v=>!v)} className="mb-2 flex w-full items-center gap-1.5 text-left text-sm font-bold text-foreground">{clientOpen?<ChevronDown className="h-4 w-4"/>:<ChevronRight className="h-4 w-4"/>}Client Emails</button>{clientOpen&&<div className="space-y-2">{templates.filter(t=>clientCodes.has(t.email_code)).sort(orderBy(clientOrder)).map(t=><button key={t.email_code} onClick={()=>{setCode(t.email_code);setMessage("");setPreview(false)}} className={"w-full rounded-lg border p-3 text-left transition "+(code===t.email_code?"border-secondary bg-secondary/40":"bg-background hover:bg-muted/40")}><div className="text-sm font-medium">{t.email_code==="primary_booking_form_reminder"?"Booking Form Reminder":t.email_name}</div><div className="mt-1 text-xs text-muted-foreground">{timing[t.email_code]??"Client email"}</div></button>)}</div>}</div><div><button type="button" onClick={()=>setScheduledOpen(v=>!v)} className="mb-2 flex w-full items-center gap-1.5 text-left text-sm font-bold text-foreground">{scheduledOpen?<ChevronDown className="h-4 w-4"/>:<ChevronRight className="h-4 w-4"/>}Scheduled Trip Emails</button>{scheduledOpen&&<div className="space-y-2">{templates.filter(t=>!clientCodes.has(t.email_code)).sort(orderBy(scheduledOrder)).map(t=><button key={t.email_code} onClick={()=>{setCode(t.email_code);setMessage("");setPreview(false)}} className={"w-full rounded-lg border p-3 text-left transition "+(code===t.email_code?"border-secondary bg-secondary/40":"bg-background hover:bg-muted/40")}><div className="text-sm font-medium">{t.email_name}</div><div className="mt-1 text-xs text-muted-foreground">{timing[t.email_code]??"Scheduled client email"}</div></button>)}</div>}</div></aside>
  <section className="space-y-5 rounded-lg border p-5">{current&&<>
   <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">{current.email_name}</h2><p className="text-sm text-muted-foreground">{timing[current.email_code]??"Edit the standard client email."}</p></div><Button variant="outline" size="sm" onClick={()=>{if(!preview)sync();setPreview(v=>!v)}}><Eye className="h-4 w-4"/>{preview?"Edit Email":"Preview Email"}</Button></div>
   {preview?<div className="rounded-lg border bg-white p-6"><div className="mb-5 border-b pb-4"><div className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Subject</div><div className="mt-1 font-semibold">{current.subject}</div></div><div className="prose prose-sm max-w-none" dangerouslySetInnerHTML={{__html:renderPreview(current.body_html)}}/></div>:<>
    <div className="space-y-2"><Label>Subject</Label><Input value={current.subject} onChange={e=>patch({subject:e.target.value})}/></div>
    <div className="space-y-2"><Label>Email Body</Label><div className="overflow-hidden rounded-md border"><div className="flex flex-wrap items-center gap-1 border-b bg-muted/30 p-2"><Button type="button" variant="ghost" size="sm" title="Bold" onClick={()=>command("bold")}><Bold className="h-4 w-4"/></Button><Button type="button" variant="ghost" size="sm" title="Italic" onClick={()=>command("italic")}><Italic className="h-4 w-4"/></Button><Button type="button" variant="ghost" size="sm" title="Bulleted list" onClick={toggleBullets}><List className="h-4 w-4"/></Button><Button type="button" variant="ghost" size="sm" title="Add link" onClick={addLink}><LinkIcon className="h-4 w-4"/></Button><span className="mx-1 h-6 w-px bg-border"/><select className="h-8 rounded-md border bg-background px-2 text-xs" defaultValue="" onChange={e=>{if(e.target.value)insert(e.target.value);e.target.value=""}}><option value="" disabled>Insert variable</option>{variables.map(([label,value])=><option key={value} value={value}>{label}</option>)}</select>{current.email_code==="trip_plans_sent"&&<Button type="button" variant="outline" size="sm" onClick={insertItinerary}><Variable className="h-4 w-4"/>Insert View Itinerary</Button>}</div><div ref={editor} contentEditable suppressContentEditableWarning onInput={sync} className="min-h-[420px] bg-background p-4 text-sm leading-7 outline-none"/></div><p className="text-xs text-muted-foreground">Use Insert Variable for personalized trip details. The View Itinerary button automatically uses the Travefy Trip Plan link stored on the Travel File.</p></div>
   </>}
   <div className="flex items-center gap-3"><Button onClick={()=>void save()} disabled={saving}>{saving?<Loader2 className="h-4 w-4 animate-spin"/>:<Save className="h-4 w-4"/>}Save Template</Button>{message&&<span className="text-sm text-muted-foreground">{message}</span>}</div>
  </>}</section>
 </div>
}
