"use client";
import{useCallback,useEffect,useState}from"react";import{X}from"lucide-react";import{Button}from"@/components/core/ui/button";import{Input}from"@/components/core/ui/input";
type Traveller={id:string;name:string;email:string|null;isPrimary:boolean};type Group={id:string;label:string;travellerIds:string[];paymentEmailRecipientTravellerId:string};
export function PaymentGroupManagerModal({travelFileId,isOpen,onClose,onSaved}:{travelFileId:string;isOpen:boolean;onClose:()=>void;onSaved:()=>void}){
 const[groups,setGroups]=useState<Group[]>([]),[travellers,setTravellers]=useState<Traveller[]>([]),[selectedId,setSelectedId]=useState("new"),[form,setForm]=useState({label:"",travellerIds:[] as string[],paymentEmailRecipientTravellerId:""}),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const load=useCallback(async()=>{const r=await fetch(`/api/travel-files/${travelFileId}/payment-groups`,{cache:"no-store"}),d=await r.json();if(!r.ok)throw new Error(d.error||"Could not load booking groups.");setGroups(d.groups??[]);setTravellers(d.travellers??[]);if(selectedId==="new"&&(d.groups??[]).length){const g=d.groups[0];setSelectedId(g.id);setForm({label:g.label||"",travellerIds:[...g.travellerIds],paymentEmailRecipientTravellerId:g.paymentEmailRecipientTravellerId||""})}},[travelFileId]);
 useEffect(()=>{if(!isOpen)return;setSelectedId("new");setForm({label:"",travellerIds:[],paymentEmailRecipientTravellerId:""});setError("");load().catch(e=>setError(e instanceof Error?e.message:"Could not load booking groups."))},[isOpen,load]);
 if(!isOpen)return null;
 function choose(id:string){setSelectedId(id);const g=groups.find(x=>x.id===id);setForm(g?{label:g.label||"",travellerIds:[...g.travellerIds],paymentEmailRecipientTravellerId:g.paymentEmailRecipientTravellerId||""}:{label:"",travellerIds:[],paymentEmailRecipientTravellerId:""});setError("")}
 function toggle(id:string){setForm(v=>{const ids=v.travellerIds.includes(id)?v.travellerIds.filter(x=>x!==id):[...v.travellerIds,id];return{...v,travellerIds:ids,paymentEmailRecipientTravellerId:ids.includes(v.paymentEmailRecipientTravellerId)?v.paymentEmailRecipientTravellerId:""}})}
 async function save(){if(!form.travellerIds.length)return setError("Choose at least one traveller for this booking group.");if(!form.paymentEmailRecipientTravellerId)return setError("Choose a payment email recipient.");setBusy(true);setError("");try{const editing=selectedId!=="new",r=await fetch(`/api/travel-files/${travelFileId}/payment-groups`,{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(editing?{...form,groupId:selectedId}:form)}),d=await r.json();if(!r.ok)throw new Error(d.error||"Could not save booking group.");await load();setSelectedId(d.group.id);setForm({label:d.group.label||"",travellerIds:[...d.group.travellerIds],paymentEmailRecipientTravellerId:d.group.paymentEmailRecipientTravellerId||""});onSaved()}catch(e){setError(e instanceof Error?e.message:"Could not save booking group.")}finally{setBusy(false)}}
 const label=(g:Group)=>{const names=g.travellerIds.map(id=>travellers.find(t=>t.id===id)?.name).filter(Boolean).join(" & ");return [g.label||"Booking group",names].filter(Boolean).join(" — ")};
 return <div className="fixed inset-0 z-[100] flex items-start justify-center bg-black/50 p-4 pt-16"><div className="max-h-[85vh] w-full max-w-2xl overflow-y-auto rounded-xl bg-background p-6 shadow-xl"><div className="flex justify-between"><div><h2 className="text-xl font-semibold">Booking / Payment Groups</h2><p className="text-sm text-muted-foreground">Create groups, assign travellers and choose who receives payment emails.</p></div><Button variant="ghost" size="sm" onClick={onClose}><X className="h-4 w-4"/></Button></div>
 <div className="mt-5 space-y-4"><label className="block space-y-1"><span className="text-sm font-medium">Group</span><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={selectedId} onChange={e=>choose(e.target.value)}><option value="new">+ Create New Booking Group</option>{groups.map(g=><option key={g.id} value={g.id}>{label(g)}</option>)}</select></label>
 <label className="block space-y-1"><span className="text-sm font-medium">Group Label <span className="font-normal text-muted-foreground">(optional)</span></span><Input placeholder="e.g. Walsh Family" value={form.label} onChange={e=>setForm(v=>({...v,label:e.target.value}))}/></label>
 <div><div className="mb-2 text-sm font-medium">Travellers *</div><div className="grid gap-2 md:grid-cols-2">{travellers.map(t=><label key={t.id} className="flex items-center gap-2 rounded-md border bg-background px-3 py-2 text-sm"><input type="checkbox" checked={form.travellerIds.includes(t.id)} onChange={()=>toggle(t.id)}/><span>{t.name}{t.isPrimary?<span className="ml-1 text-xs text-muted-foreground">(Primary)</span>:null}</span></label>)}</div></div>
 <label className="block space-y-1"><span className="text-sm font-medium">Payment Email Recipient *</span><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={form.paymentEmailRecipientTravellerId} onChange={e=>setForm(v=>({...v,paymentEmailRecipientTravellerId:e.target.value}))}><option value="">Choose recipient</option>{travellers.filter(t=>t.email&&form.travellerIds.includes(t.id)).map(t=><option key={t.id} value={t.id}>{t.name} — {t.email}</option>)}</select><span className="text-xs text-muted-foreground">Only travellers in this group with an email address on file are available.</span></label>
 {error&&<p className="text-sm text-destructive">{error}</p>}<div className="flex justify-end gap-2"><Button variant="outline" onClick={onClose} disabled={busy}>Close</Button><Button onClick={save} disabled={busy}>{busy?"Saving...":selectedId==="new"?"Create Group":"Save Group Changes"}</Button></div></div></div></div>
}