"use client";
import{useEffect,useState}from"react";import{Loader2,X}from"lucide-react";import{Button}from"@/components/core/ui/button";
type EmailPlan={email_code:string;email_name:string;enabled:boolean;scheduled_date:string|null;timing_note:string;sequence_order:number;sent_at:string|null};
export function PreTripEmailConfigModal({travelFileId,isOpen,onClose}:{travelFileId:string;isOpen:boolean;onClose:()=>void}){
const[emails,setEmails]=useState<EmailPlan[]>([]),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(null);
useEffect(()=>{if(!isOpen)return;setLoading(true);setError(null);fetch(`/api/travel-files/${travelFileId}/pretrip-email-plan`,{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error??"Could not load pre-trip emails.");setEmails(d.emails??[])}).catch(e=>setError(e instanceof Error?e.message:"Could not load pre-trip emails.")).finally(()=>setLoading(false))},[isOpen,travelFileId]);
if(!isOpen)return null;
function patch(code:string,change:Partial<EmailPlan>){setEmails(v=>v.map(e=>e.email_code===code?{...e,...change}:e))}
async function confirm(){const today=new Intl.DateTimeFormat("en-CA",{timeZone:"America/Edmonton",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date()),due=emails.filter(e=>e.enabled&&!e.sent_at&&e.scheduled_date&&e.scheduled_date<=today);if(due.length&&!window.confirm(`${due.length} email${due.length===1?" is":"s are"} due today or earlier. ${due.length===1?"It":"They"} will send automatically at 8:00 a.m. MDT tomorrow. Save anyway?`))return;setSaving(true);setError(null);setNotice(null);try{const r=await fetch(`/api/travel-files/${travelFileId}/pretrip-email-plan`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({emails:emails.map(e=>({email_code:e.email_code,enabled:e.enabled,scheduled_date:e.scheduled_date}))})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error??"Could not save pre-trip email plan.");onClose()}catch(e){setError(e instanceof Error?e.message:"Could not save pre-trip email plan.")}finally{setSaving(false)}}
return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="flex max-h-[calc(100dvh-2rem)] w-full max-w-3xl flex-col overflow-hidden rounded-lg bg-background shadow-xl"><div className="flex items-start border-b px-6 py-5"><div><h2 className="text-lg font-semibold">Configure Pre-Trip Emails</h2><p className="mt-1 text-sm text-muted-foreground">Choose which client emails should be sent and adjust their scheduled dates.</p></div><button type="button" className="ml-auto" onClick={onClose}><X className="h-5 w-5"/></button></div><div className="min-h-0 flex-1 overflow-y-auto p-6">{loading?<div className="flex items-center gap-2 text-sm text-muted-foreground"><Loader2 className="h-4 w-4 animate-spin"/>Loading email schedule...</div>:<div className="space-y-2">{emails.map(e=><div key={e.email_code} className={`grid gap-3 rounded-lg border p-3 sm:grid-cols-[28px_minmax(0,1fr)_230px] sm:items-center ${e.enabled?"":"bg-muted/20 opacity-70"}`}><input aria-label={`Send ${e.email_name}`} type="checkbox" checked={e.enabled} onChange={x=>patch(e.email_code,{enabled:x.target.checked})} className="h-4 w-4"/><div><div className="flex items-center gap-2"><div className="text-sm font-medium">{e.email_name}</div>{e.sent_at?<span className="rounded-full bg-muted px-2 py-0.5 text-[11px] font-medium text-muted-foreground">Sent</span>:<span className="rounded-full border px-2 py-0.5 text-[11px] font-medium text-muted-foreground">Not sent</span>}</div><div className="text-xs text-muted-foreground">{e.sent_at?`Sent ${new Date(e.sent_at).toLocaleString("en-CA",{timeZone:"America/Edmonton",month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit"})}`:e.timing_note}</div></div><div className="flex items-center gap-2"><input type="date" value={e.scheduled_date??""} disabled={!e.enabled||Boolean(e.sent_at)} onChange={x=>patch(e.email_code,{scheduled_date:x.target.value||null})} className="h-10 min-w-0 flex-1 rounded-md border bg-background px-3 text-sm"/>{e.sent_at&&<span className="text-xs text-muted-foreground">Sent</span>}</div></div>)}</div>}{error&&<p className="mt-4 text-sm text-destructive">{error}</p>}</div><div className="flex items-center justify-between gap-3 border-t p-4"><p className="text-xs text-muted-foreground">Save updates the email schedule. Due emails are sent automatically each morning at 8:00 a.m. MDT.</p><div className="flex gap-2"><Button variant="outline" onClick={onClose} disabled={saving}>Cancel</Button><Button onClick={()=>void confirm()} disabled={saving||loading}>{saving&&<Loader2 className="h-4 w-4 animate-spin"/>}Save Email Schedule</Button></div></div></div></div>}
