"use client";
import{useEffect,useState}from"react";import{Loader2,X}from"lucide-react";import{Button}from"@/components/core/ui/button";
type EmailPlan={email_code:string;email_name:string;enabled:boolean;scheduled_date:string|null;timing_note:string;sequence_order:number;sent_at:string|null};
export function PreTripEmailConfigModal({travelFileId,isOpen,onClose,onComplete}:{travelFileId:string;isOpen:boolean;onClose:()=>void;onComplete:()=>Promise<void>}){
const[emails,setEmails]=useState<EmailPlan[]>([]),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(null);
useEffect(()=>{if(!isOpen)return;setLoading(true);setError(null);fetch(`/api/travel-files/${travelFileId}/pretrip-email-plan`,{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error??"Could not load pre-trip emails.");setEmails(d.emails??[])}).catch(e=>setError(e instanceof Error?e.message:"Could not load pre-trip emails.")).finally(()=>setLoading(false))},[isOpen,travelFileId]);
if(!isOpen)return null;
function patch(code:string,change:Partial<EmailPlan>){setEmails(v=>v.map(e=>e.email_code===code?{...e,...change}:e))}
async function confirm(){setSaving(true);setError(null);try{const r=await fetch(`/api/travel-files/${travelFileId}/pretrip-email-plan`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({emails:emails.map(e=>({email_code:e.email_code,enabled:e.enabled,scheduled_date:e.scheduled_date}))})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error??"Could not save pre-trip email plan.");await onComplete();onClose()}catch(e){setError(e instanceof Error?e.message:"Could not save pre-trip email plan.")}finally{setSaving(false)}}
return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="flex max-h-[calc(100dvh-2rem)] w-full max-w-3xl flex-col overflow-hidden rounded-lg bg-background shadow-xl"><div className="flex items-start border-b px-6 py-5"><div><h2 className="text-lg font-semibold">Configure Pre-Trip Emails</h2><p className="mt-1 text-sm text-muted-foreground">Choose which client emails should be sent and adjust any dates before completing Invoicing & Itinerary.</p></div><button type="button" className="ml-auto" onClick={onClose}><X className="h-5 w-5"/></button></div><div className="min-h-0 flex-1 overflow-y-auto p-6">{loading?<div className="flex items-center gap-2 text-sm text-muted-foreground"><Loader2 className="h-4 w-4 animate-spin"/>Loading email schedule...</div>:<div className="space-y-2">{emails.map(e=><div key={e.email_code} className={`grid gap-3 rounded-lg border p-3 sm:grid-cols-[28px_minmax(0,1fr)_170px] sm:items-center ${e.enabled?"":"bg-muted/20 opacity-70"}`}><input aria-label={`Send ${e.email_name}`} type="checkbox" checked={e.enabled} onChange={x=>patch(e.email_code,{enabled:x.target.checked})} className="h-4 w-4"/><div><div className="text-sm font-medium">{e.email_name}</div><div className="text-xs text-muted-foreground">{e.timing_note}</div></div><input type="date" value={e.scheduled_date??""} disabled={!e.enabled||Boolean(e.sent_at)} onChange={x=>patch(e.email_code,{scheduled_date:x.target.value||null})} className="h-10 rounded-md border bg-background px-3 text-sm"/></div>)}</div>}{error&&<p className="mt-4 text-sm text-destructive">{error}</p>}</div><div className="flex items-center justify-between gap-3 border-t p-4"><p className="text-xs text-muted-foreground">These dates are saved to the Travel File. Briitely automation will be connected in the next step.</p><div className="flex gap-2"><Button variant="outline" onClick={onClose} disabled={saving}>Cancel</Button><Button onClick={()=>void confirm()} disabled={saving||loading}>{saving&&<Loader2 className="h-4 w-4 animate-spin"/>Save & Complete Invoicing</Button></div></div></div></div>}
