"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Loader2, Send, X } from "lucide-react";
import { Button } from "@/components/core/ui/button";
import { Input } from "@/components/core/ui/input";
import { Label } from "@/components/core/ui/label";

type Props = { travelFileId: string; isOpen: boolean; onClose: () => void };
const first = (v: string) => v.trim().split(/\s+/)[0] || "there";
const advisorFirst = (v: string) => v.trim().split(/\s+/)[0] || "Your Inspired Vacations Advisor";
function makeEmail(name: string, url: string, advisor: string) {
  return `<div>Hi ${first(name)},</div><div><br></div><div>Exciting news — your personalized travel proposal is ready! 🎉 We've crafted it just for you, packed with options and ideas to make your trip unforgettable.</div><div><br></div><div>You should also see it from Travefy in your inbox. If it doesn't appear, please check your spam or junk folder.</div><div><br></div><div>👉 <a href="${url}" style="text-decoration: underline;">View Your Custom Trip Proposal</a></div><div><br></div><div>Take your time to explore it, and if you have any questions, want to tweak something, or just want to chat about your options, we're here and happy to help. Just hit reply on this email and we'll get back to you! 🌺</div><div><br></div><div>We can't wait to hear what you think!</div><div><br></div><div>Cheers,</div><div><br></div><div>${advisorFirst(advisor)} &amp; the Inspired Vacations Team ✈️</div>`;
}
export function SendProposalModal({ travelFileId, isOpen, onClose }: Props) {
  const router = useRouter();
  const [url, setUrl] = useState(""); const [sent, setSent] = useState(false); const [email, setEmail] = useState("");
  const [clientName, setClientName] = useState("Client"); const [advisor, setAdvisor] = useState("Your Inspired Vacations Advisor");
  const [prepared, setPrepared] = useState(false); const [subject, setSubject] = useState("🌴 Your Custom Trip Proposal is Ready! ✈️");
  const [html, setHtml] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null);
  useEffect(() => { if (!isOpen) return; setPrepared(false); setSent(false); setError(null); fetch(`/api/travel-files/${travelFileId}/proposal-send`).then(r => r.json()).then(d => { setUrl(d.travefyProposalUrl ?? ""); setEmail(d.email ?? ""); setClientName(d.clientName ?? d.firstName ?? "Client"); setAdvisor(d.assignedAdvisorName ?? "Your Inspired Vacations Advisor"); }).catch(() => {}); }, [isOpen, travelFileId]);
  async function prepare(e: React.FormEvent) { e.preventDefault(); setLoading(true); setError(null); try { const r = await fetch(`/api/travel-files/${travelFileId}/proposal-send`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "prepare", sentViaTravefy: sent, travefyProposalUrl: url }) }); const d = await r.json().catch(() => ({})); if (!r.ok) throw new Error(d.error ?? "Could not prepare proposal email."); setHtml(makeEmail(clientName, d.travefyProposalUrl, advisor)); setPrepared(true); } catch (e) { setError(e instanceof Error ? e.message : "Could not prepare proposal email."); } finally { setLoading(false); } }
  async function sendEmail() { setLoading(true); setError(null); try { const s = await fetch(`/api/travel-files/${travelFileId}/send-client-email`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ emailType: "proposal", recipientName: clientName, recipientEmail: email, subject, htmlBody: html }) }); const sd = await s.json().catch(() => ({})); if (!s.ok) throw new Error(sd.error ?? "Could not send proposal email through Briitely."); const r = await fetch(`/api/travel-files/${travelFileId}/proposal-send`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "mark-sent" }) }); const d = await r.json().catch(() => ({})); if (!r.ok) throw new Error(d.error ?? "Email sent, but the Travel File could not be advanced."); onClose(); router.refresh(); } catch (e) { setError(e instanceof Error ? e.message : "Could not send proposal email."); } finally { setLoading(false); } }
  if (!isOpen) return null;
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="w-full max-w-2xl rounded-lg bg-background shadow-xl"><div className="flex items-center border-b px-6 py-5"><h2 className="text-lg font-semibold">Send Proposal</h2><button type="button" className="ml-auto" onClick={onClose}><X className="h-5 w-5" /></button></div>{!prepared ? <form onSubmit={prepare}><div className="space-y-5 p-6"><div className="space-y-2"><Label>Travefy Proposal URL *</Label><Input type="url" value={url} onChange={e => setUrl(e.target.value)} required /><p className="text-xs text-muted-foreground">This will be saved to Booking & Planning on the Travel File.</p></div><label className="flex items-start gap-3 rounded-md border p-4"><input type="checkbox" checked={sent} onChange={e => setSent(e.target.checked)} className="mt-1 h-4 w-4" required /><span><span className="block text-sm font-medium">Have you sent the proposal via Travefy? *</span><span className="block text-xs text-muted-foreground">Confirm the Travefy proposal has been sent before preparing the follow-up email.</span></span></label>{error && <p className="text-sm text-destructive">{error}</p>}</div><div className="flex justify-end gap-2 border-t p-4"><Button size="sm" type="button" variant="outline" onClick={onClose}>Cancel</Button><Button size="sm" type="submit" disabled={loading}>{loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}Prepare Email</Button></div></form> : <div className="space-y-4 p-5"><p className="text-sm">To: {clientName} &lt;{email}&gt;</p><label className="block text-sm font-medium">Subject<input className="mt-1 w-full rounded-md border px-3 py-2 text-sm" value={subject} onChange={e => setSubject(e.target.value)} /></label><div><div className="mb-1 text-sm font-medium">Message</div><div className="min-h-64 rounded-md border p-3 text-sm leading-5 outline-none [&_a]:text-primary [&_a]:underline" contentEditable suppressContentEditableWarning dangerouslySetInnerHTML={{ __html: html }} onInput={e => setHtml(e.currentTarget.innerHTML)} /></div>{error && <p className="text-sm text-destructive">{error}</p>}<div className="flex justify-end gap-2"><Button size="sm" variant="outline" onClick={() => setPrepared(false)}>Back</Button><Button size="sm" onClick={sendEmail} disabled={loading || !email || !subject.trim() || !html.trim()}>{loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}Send through Briitely</Button></div></div>}</div></div>;
}
