"use client";

import {useEffect,useState} from "react";
import {createPortal} from "react-dom";
import {ClipboardCheck,Trash2} from "lucide-react";
import {Button} from "@/components/core/ui/button";
import {DeleteTravelFileDialog} from "@/components/app/delete-travel-file-dialog";
import {CompleteConsultationModal} from "@/components/app/complete-consultation-modal";
import {CurrentActionTasks} from "@/components/app/current-action-tasks";

interface TravelFileActionsProps {travelFileId:string;clientName:string;destination:string|null;tripType:string|null;travelTimeframe:string|null;departureDate:string|null;returnDate:string|null;numberOfAdults:number|null;numberOfChildren:number|null;childrenAges:string|null;budgetRange:string|null;insuranceInterest:string|null;specialConsiderations:string|null;staffNotes:string|null;assignedAdvisorId:string|null;canEdit:boolean;canDelete:boolean;stage:string;currentActionCode:string|null;currentActionStatus:string|null;previousNotes:Array<{id:string;note_type:string;note_text:string;created_at:string;author:{id:string;full_name:string}|null}>;}

export function TravelFileActions(props:TravelFileActionsProps){
 const[deleteOpen,setDeleteOpen]=useState(false);const[consultOpen,setConsultOpen]=useState(false);const[actionMount,setActionMount]=useState<HTMLElement|null>(null);const[tasksMount,setTasksMount]=useState<HTMLElement|null>(null);
 const showConsult=props.canEdit&&props.currentActionStatus==="active"&&props.currentActionCode==="complete_initial_consultation";
 useEffect(()=>{let action:HTMLElement|null=null,tasks:HTMLElement|null=null;const panels=[...document.querySelectorAll("main > div")];const workflow=panels.find(el=>el.textContent?.includes("Current action")&&el.textContent?.includes("Due / Waiting")) as HTMLElement|undefined;if(!workflow)return;const details=workflow.querySelector(".md\\:grid-cols-\\[220px_minmax\\(0\\,1fr\\)\\] > div:nth-child(2)") as HTMLElement|null;if(!details)return;const infoRow=[...details.querySelectorAll("div")].find(el=>el.textContent?.includes("Responsible")&&el.textContent?.includes("Due / Waiting")&&el.className.includes("mt-4")) as HTMLElement|undefined;if(infoRow){infoRow.className="mt-4 grid gap-4 sm:grid-cols-3 sm:items-end";const infoGrid=infoRow.firstElementChild as HTMLElement|null;if(infoGrid){infoGrid.className="grid gap-4 sm:col-span-2 sm:grid-cols-2"}action=document.createElement("div");action.className="min-h-9";infoRow.appendChild(action);setActionMount(action)}tasks=document.createElement("div");details.appendChild(tasks);setTasksMount(tasks);return()=>{action?.remove();tasks?.remove()};},[props.travelFileId,props.currentActionCode,props.currentActionStatus]);
 return <>{props.canDelete&&<Button variant="destructive" size="sm" onClick={()=>setDeleteOpen(true)}><Trash2 className="h-4 w-4"/>Delete Travel File</Button>}{actionMount&&showConsult&&createPortal(<Button size="sm" className="w-full sm:w-auto" onClick={()=>setConsultOpen(true)}><ClipboardCheck className="h-4 w-4"/>Complete Initial Consultation</Button>,actionMount)}{tasksMount&&props.currentActionStatus==="active"&&createPortal(<CurrentActionTasks travelFileId={props.travelFileId}/>,tasksMount)}{showConsult&&consultOpen&&<CompleteConsultationModal key={`consult-${props.travelFileId}-${consultOpen}`} travelFileId={props.travelFileId} clientName={props.clientName} destination={props.destination} tripType={props.tripType} travelTimeframe={props.travelTimeframe} departureDate={props.departureDate} returnDate={props.returnDate} numberOfAdults={props.numberOfAdults} numberOfChildren={props.numberOfChildren} childrenAges={props.childrenAges} budgetRange={props.budgetRange} specialConsiderations={props.specialConsiderations} insuranceInterest={props.insuranceInterest} assignedAdvisorId={props.assignedAdvisorId} staffNotes={props.staffNotes} previousNotes={props.previousNotes} isOpen={consultOpen} onClose={()=>setConsultOpen(false)}/>} {props.canDelete&&<DeleteTravelFileDialog travelFileId={props.travelFileId} clientName={props.clientName} destination={props.destination} tripType={props.tripType} isOpen={deleteOpen} onClose={()=>setDeleteOpen(false)}/>}</>;
}
