"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Loader2, Pencil, X } from "lucide-react";
import { Button } from "@/components/core/ui/button";
import { Input } from "@/components/core/ui/input";
import { Label } from "@/components/core/ui/label";
import { budgetRangeOptions, intakeMethodOptions, referralSourceOptions, tripTypeOptions } from "@/lib/travel/tag-mappings";

type Section = "trip" | "inquiry" | "booking" | "insurance" | "assignment";

type Values = Record<string, string | number | boolean | null | undefined>;

export function TravelFileSectionEditor({
  travelFileId,
  updatedAt,
  section,
  values,
}: {
  travelFileId: string;
  updatedAt: string;
  section: Section;
  values: Values;
}) {
  const [open, setOpen] = useState(false);
  return <>
    <Button variant="outline" size="sm" onClick={() => setOpen(true)}><Pencil className="h-4 w-4"/>Edit</Button>
    {open && <SectionModal travelFileId={travelFileId} updatedAt={updatedAt} section={section} values={values} onClose={() => setOpen(false)} />}
  </>;
}

const titles: Record<Section,string> = { trip:"Trip Details", inquiry:"Inquiry Details", booking:"Booking & Planning", insurance:"Insurance & Pre-Trip", assignment:"Assignment" };
const selectClass="h-10 w-full rounded-md border border-input bg-background px-3 text-sm";

function SectionModal({travelFileId,updatedAt,section,values,onClose}:{travelFileId:string;updatedAt:string;section:Section;values:Values;onClose:()=>void}){
  const router=useRouter();
  const[form,setForm]=useState<Record<string,string>>(()=>Object.fromEntries(Object.entries(values).map(([k,v])=>[k,v==null?"":String(v)])));
  const[saving,setSaving]=useState(false);const[error,setError]=useState<string|null>(null);const[advisors,setAdvisors]=useState<Array<{id:string;full_name:string}>>([]);
  const set=(key:string,value:string)=>setForm(prev=>({...prev,[key]:value}));
  useEffect(()=>{if(section!=="assignment")return;fetch("/api/travel-files/advisors").then(r=>r.ok?r.json():null).then(d=>setAdvisors(d?.advisors??[])).catch(()=>{})},[section]);
  async function save(e:React.FormEvent){e.preventDefault();setSaving(true);setError(null);const payload:Record<string,unknown>={updatedAt};
    if(section==="trip")Object.assign(payload,{destination:form.destination,tripType:form.tripType,travelTimeframe:form.travelTimeframe,departureDate:form.departureDate||null,returnDate:form.returnDate||null,budgetRange:form.budgetRange,specialConsiderations:form.specialConsiderations||null});
    if(section==="inquiry")Object.assign(payload,{inquirySource:form.inquirySource,intakeMethod:form.intakeMethod,referralDetail:form.referralDetail||null,eventDetail:form.eventDetail||null,staffNotes:form.staffNotes||null,internalNotes:form.internalNotes||null});
    if(section==="booking")Object.assign(payload,{proposalDueDate:form.proposalDueDate||null,dateBooked:form.dateBooked||null,totalBookingValue:form.totalBookingValue?Number(form.totalBookingValue):null,tmfAmount:form.tmfAmount?Number(form.tmfAmount):null,ivtCustom:form.ivtCustom===""?null:form.ivtCustom==="true",clientbaseResCardId:form.clientbaseResCardId||null,primaryBookingNumber:form.primaryBookingNumber||null,travefyProposalUrl:form.travefyProposalUrl||null,travefyTripPlanUrl:form.travefyTripPlanUrl||null});
    if(section==="insurance")Object.assign(payload,{insuranceInterest:form.insuranceInterest||null,insuranceStatus:form.insuranceStatus,insuranceWaiverSigned:form.insuranceWaiverSigned===""?null:form.insuranceWaiverSigned==="true",pretripMeetingRequired:form.pretripMeetingRequired===""?null:form.pretripMeetingRequired==="true",pretripMeetingBookedAt:form.pretripMeetingBookedAt||null,pretripCardSentAt:form.pretripCardSentAt||null,bookingRegistrationEligible:form.bookingRegistrationEligible==="true",bookingRegistrationDoneAt:form.bookingRegistrationDoneAt||null});
    if(section==="assignment")Object.assign(payload,{assignedAdvisorId:form.assignedAdvisorId||null});
    try{const r=await fetch(`/api/travel-files/${encodeURIComponent(travelFileId)}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.error??"Could not save changes.");onClose();router.refresh()}catch(err){setError(err instanceof Error?err.message:"Could not save changes.")}finally{setSaving(false)}}
  return <div className="fixed inset-0 z-50 flex items-start justify-center overflow-y-auto bg-black/50 p-4 sm:p-8"><div className="my-4 w-full max-w-3xl rounded-xl bg-background shadow-xl"><div className="flex items-start justify-between border-b border-border px-5 py-4"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-primary">Travel File</p><h2 className="mt-1 text-lg font-semibold">Edit {titles[section]}</h2></div><Button variant="ghost" size="sm" onClick={onClose} disabled={saving}><X className="h-4 w-4"/></Button></div><form onSubmit={save} className="p-5"><div className="grid gap-5 md:grid-cols-[150px_1fr]"><aside><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{titles[section]}</p><p className="mt-1 text-xs text-muted-foreground">Update only this section.</p></aside><div className="space-y-4">{section==="trip"&&<TripFields form={form} set={set}/>} {section==="inquiry"&&<InquiryFields form={form} set={set}/>} {section==="booking"&&<BookingFields form={form} set={set}/>} {section==="insurance"&&<InsuranceFields form={form} set={set}/>} {section==="assignment"&&<Field label="Assigned Advisor"><select className={selectClass} value={form.assignedAdvisorId??""} onChange={e=>set("assignedAdvisorId",e.target.value)}><option value="">Unassigned</option>{advisors.map(a=><option key={a.id} value={a.id}>{a.full_name}</option>)}</select></Field>}{error&&<p className="text-sm text-destructive">{error}</p>}<div className="flex justify-end gap-2 border-t border-border pt-4"><Button type="button" variant="outline" onClick={onClose} disabled={saving}>Cancel</Button><Button type="submit" disabled={saving}>{saving&&<Loader2 className="h-4 w-4 animate-spin"/>}{saving?"Saving...":"Save Changes"}</Button></div></div></div></form></div></div>
}
function TripFields({form,set}:{form:Record<string,string>;set:(k:string,v:string)=>void}){return <><div className="grid gap-3 sm:grid-cols-2"><Field label="Destination"><Input value={form.destination??""} onChange={e=>set("destination",e.target.value)}/></Field><Field label="Trip Type"><select className={selectClass} value={form.tripType??""} onChange={e=>set("tripType",e.target.value)}><option value="">Select...</option>{tripTypeOptions.map(o=><option key={o}>{o}</option>)}</select></Field><Field label="Travel Timeframe"><Input value={form.travelTimeframe??""} onChange={e=>set("travelTimeframe",e.target.value)}/></Field><Field label="Budget Range"><select className={selectClass} value={form.budgetRange??""} onChange={e=>set("budgetRange",e.target.value)}><option value="">Select...</option>{budgetRangeOptions.map(o=><option key={o}>{o}</option>)}</select></Field><Field label="Departure Date"><Input type="date" value={form.departureDate??""} onChange={e=>set("departureDate",e.target.value)}/></Field><Field label="Return Date"><Input type="date" value={form.returnDate??""} onChange={e=>set("returnDate",e.target.value)}/></Field></div><Field label="Special Considerations"><textarea className="min-h-20 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" value={form.specialConsiderations??""} onChange={e=>set("specialConsiderations",e.target.value)}/></Field></>}
function InquiryFields({form,set}:{form:Record<string,string>;set:(k:string,v:string)=>void}){return <><div className="grid gap-3 sm:grid-cols-2"><Field label="Inquiry Source"><Input value={form.inquirySource??""} onChange={e=>set("inquirySource",e.target.value)}/></Field><Field label="Intake Method"><select className={selectClass} value={form.intakeMethod??""} onChange={e=>set("intakeMethod",e.target.value)}>{intakeMethodOptions.map(o=><option key={o}>{o}</option>)}</select></Field><Field label="Referral Detail"><Input value={form.referralDetail??""} onChange={e=>set("referralDetail",e.target.value)}/></Field><Field label="Event Detail"><Input value={form.eventDetail??""} onChange={e=>set("eventDetail",e.target.value)}/></Field></div><Field label="Staff Notes"><textarea className="min-h-20 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" value={form.staffNotes??""} onChange={e=>set("staffNotes",e.target.value)}/></Field><Field label="Internal Notes"><textarea className="min-h-20 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" value={form.internalNotes??""} onChange={e=>set("internalNotes",e.target.value)}/></Field></>}
function BookingFields({form,set}:{form:Record<string,string>;set:(k:string,v:string)=>void}){return <><div className="grid gap-3 sm:grid-cols-2"><Field label="Proposal Due Date"><Input type="date" value={form.proposalDueDate??""} onChange={e=>set("proposalDueDate",e.target.value)}/></Field><Field label="Date Booked"><Input type="date" value={form.dateBooked??""} onChange={e=>set("dateBooked",e.target.value)}/></Field><Field label="Total Booking Value"><Input type="number" min="0" step="0.01" value={form.totalBookingValue??""} onChange={e=>set("totalBookingValue",e.target.value)}/></Field><Field label="TMF Amount"><Input type="number" min="0" step="0.01" value={form.tmfAmount??""} onChange={e=>set("tmfAmount",e.target.value)}/></Field><Field label="IVT / Custom"><select className={selectClass} value={form.ivtCustom??""} onChange={e=>set("ivtCustom",e.target.value)}><option value="">Not set</option><option value="true">Yes</option><option value="false">No</option></select></Field><Field label="ClientBase Res Card ID"><Input value={form.clientbaseResCardId??""} onChange={e=>set("clientbaseResCardId",e.target.value)}/></Field></div><Field label="Primary Booking Number"><Input value={form.primaryBookingNumber??""} onChange={e=>set("primaryBookingNumber",e.target.value)}/></Field><Field label="Travefy Proposal URL"><Input type="url" value={form.travefyProposalUrl??""} onChange={e=>set("travefyProposalUrl",e.target.value)}/></Field><Field label="Travefy Trip Plan URL"><Input type="url" value={form.travefyTripPlanUrl??""} onChange={e=>set("travefyTripPlanUrl",e.target.value)}/></Field></>}
function InsuranceFields({form,set}:{form:Record<string,string>;set:(k:string,v:string)=>void}){const yn=(key:string)=><select className={selectClass} value={form[key]??""} onChange={e=>set(key,e.target.value)}><option value="">Not set</option><option value="true">Yes</option><option value="false">No</option></select>;return <><div className="grid gap-3 sm:grid-cols-2"><Field label="Insurance Preference"><Input value={form.insuranceInterest??""} onChange={e=>set("insuranceInterest",e.target.value)}/></Field><Field label="Insurance Status"><select className={selectClass} value={form.insuranceStatus??"pending"} onChange={e=>set("insuranceStatus",e.target.value)}><option value="pending">Pending</option><option value="accepted">Accepted</option><option value="declined">Declined</option><option value="not_required">Not Required</option></select></Field><Field label="Waiver Signed">{yn("insuranceWaiverSigned")}</Field><Field label="Pre-Trip Meeting Required">{yn("pretripMeetingRequired")}</Field><Field label="Pre-Trip Meeting Booked"><Input type="date" value={form.pretripMeetingBookedAt??""} onChange={e=>set("pretripMeetingBookedAt",e.target.value)}/></Field><Field label="Pre-Trip Card Sent"><Input type="date" value={form.pretripCardSentAt??""} onChange={e=>set("pretripCardSentAt",e.target.value)}/></Field><Field label="Booking Registration Eligible">{yn("bookingRegistrationEligible")}</Field><Field label="Booking Registration Completed"><Input type="date" value={form.bookingRegistrationDoneAt??""} onChange={e=>set("bookingRegistrationDoneAt",e.target.value)}/></Field></div></>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-1.5"><Label className="text-xs">{label}</Label>{children}</div>}
