"use client";
import{useCallback,useEffect,useState}from"react";import{useRouter}from"next/navigation";import{AlertTriangle,Loader2,X}from"lucide-react";import{Button}from"@/components/core/ui/button";import{Card,CardContent,CardHeader,CardTitle}from"@/components/core/ui/card";import{Input}from"@/components/core/ui/input";import{Label}from"@/components/core/ui/label";import{Badge}from"@/components/core/ui/badge";
interface Advisor{id:string;full_name:string}
interface Props{travelFileId:string;currentStage:string;currentActionCode:string|null;currentActionStatus:string|null;currentResponsibleType:string|null;currentResponsibleName:string|null;isOpen:boolean;onClose:()=>void}
const OPTIONS=[
{actionCode:"book_initial_consultation",label:"New Inquiry — Book Initial Consultation",responsibleType:"client"},
{actionCode:"complete_initial_consultation",label:"Consult Booked — Complete Initial Consultation",responsibleType:"internal"},
{actionCode:"send_tmf_agreement",label:"Consultation Complete — Prepare Retainer Email",responsibleType:"internal"},
{actionCode:"await_tmf_and_booking_form",label:"Retainer Sent — Await Agreement / Booking Forms",responsibleType:"client"},
{actionCode:"collect_tmf_payment",label:"Retainer Processing — Collect Retainer Payment",responsibleType:"internal"},
{actionCode:"assign_proposal",label:"Planning / Proposal — Assign Proposal",responsibleType:"internal"},
{actionCode:"create_proposal",label:"Planning / Proposal — Create Proposal",responsibleType:"internal"},
{actionCode:"send_proposal",label:"Planning / Proposal — Send Proposal",responsibleType:"internal"},
{actionCode:"check_proposal_status",label:"Proposal Sent — Check Proposal Status",responsibleType:"internal"},
{actionCode:"negotiate_proposal",label:"Negotiating — Manage Negotiation",responsibleType:"internal"},
{actionCode:"complete_booking",label:"Proposal Accepted — Complete Booking",responsibleType:"internal"},
{actionCode:"invoicing_itinerary",label:"Booking Complete — Invoicing & Itinerary",responsibleType:"internal"},
{actionCode:"waiting_for_travel",label:"Booking Complete — Waiting for Travel",responsibleType:"system"},
{actionCode:"post_trip_close_file",label:"Post-Trip — Close File",responsibleType:"internal"},
] as const;
export function WorkflowOverrideModal({travelFileId,currentStage,currentActionCode,currentActionStatus,currentResponsibleName,isOpen,onClose}:Props){
 const router=useRouter(),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(null),[advisors,setAdvisors]=useState<Advisor[]>([]),[actionCode,setActionCode]=useState(currentActionCode==="confirm_booking"?"complete_booking":currentActionCode??""),[responsibleUserId,setResponsibleUserId]=useState(""),[dueAt,setDueAt]=useState("");
 const loadAdvisors=useCallback(async()=>{try{const r=await fetch("/api/travel-files/advisors");if(r.ok)setAdvisors((await r.json()).advisors??[])}catch{}},[]);
 useEffect(()=>{if(isOpen)void loadAdvisors()},[isOpen,loadAdvisors]);
 if(!isOpen)return null;
 const selected=OPTIONS.find(x=>x.actionCode===actionCode),currentLabel=OPTIONS.find(x=>x.actionCode===(currentActionCode==="confirm_booking"?"complete_booking":currentActionCode))?.label??currentActionCode??"None";
 async function submit(e:React.FormEvent){e.preventDefault();if(!selected)return setError("Select a workflow step.");if(selected.responsibleType==="internal"&&!responsibleUserId)return setError("Select the responsible user.");setSaving(true);setError(null);try{const r=await fetch(`/api/travel-files/${travelFileId}/override`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({actionCode,responsibleUserId:selected.responsibleType==="internal"?responsibleUserId:null,dueAt:dueAt||null})}),d=await r.json();if(!r.ok)throw new Error(d.error??"Failed to override workflow.");onClose();router.refresh()}catch(e){setError(e instanceof Error?e.message:"Something went wrong.")}finally{setSaving(false)}}
 return <div className="fixed inset-0 z-50 flex items-center justify-center overflow-y-auto bg-black/50 p-4"><Card className="flex max-h-[calc(100dvh-2rem)] w-full max-w-lg flex-col overflow-hidden shadow-xl"><CardHeader className="shrink-0 flex-row items-center justify-between space-y-0 border-b"><CardTitle className="flex items-center gap-2"><AlertTriangle className="h-5 w-5"/>Override Workflow</CardTitle><button onClick={onClose}><X className="h-5 w-5"/></button></CardHeader><form onSubmit={submit} className="flex min-h-0 flex-1 flex-col overflow-hidden"><div className="min-h-0 flex-1 overflow-y-auto"><CardContent className="space-y-5 p-6"><div className="rounded-lg border bg-muted/30 p-3 text-sm">Manual operational override. The selected workflow step sets the matching stage and next action together. Existing actions remain in history.</div><div className="grid gap-3 sm:grid-cols-2"><div><span className="text-xs text-muted-foreground">Stage</span><div><Badge variant="outline">{currentStage}</Badge></div></div><div><span className="text-xs text-muted-foreground">Current Action</span><p className="text-sm font-medium">{currentLabel}</p></div><div><span className="text-xs text-muted-foreground">Status</span><p className="text-sm capitalize">{currentActionStatus??"—"}</p></div><div><span className="text-xs text-muted-foreground">Responsible</span><p className="text-sm">{currentResponsibleName??"—"}</p></div></div><Field label="Move to"><select value={actionCode} onChange={e=>{setActionCode(e.target.value);setResponsibleUserId("")}} className="h-10 w-full rounded-md border bg-background px-3 text-sm"><option value="">Select a workflow step...</option>{OPTIONS.map(x=><option key={x.actionCode} value={x.actionCode}>{x.label}</option>)}</select></Field>{selected?.responsibleType==="internal"?<Field label="Responsible User"><select value={responsibleUserId} onChange={e=>setResponsibleUserId(e.target.value)} className="h-10 w-full rounded-md border bg-background px-3 text-sm"><option value="">Select a user...</option>{advisors.map(a=><option key={a.id} value={a.id}>{a.full_name}</option>)}</select></Field>:selected&&<Field label="Responsible"><div className="rounded-md border bg-muted/20 px-3 py-2 text-sm capitalize">{selected.responsibleType}</div></Field>}<Field label="Due Date / Time (optional)"><Input type="datetime-local" value={dueAt} onChange={e=>setDueAt(e.target.value)}/></Field>{error&&<p className="text-sm text-destructive">{error}</p>}</CardContent></div><div className="shrink-0 flex justify-end gap-3 border-t bg-background p-4"><Button type="button" variant="outline" onClick={onClose}>Cancel</Button><Button type="submit" disabled={saving}>{saving&&<Loader2 className="h-4 w-4 animate-spin"/>}Apply Override</Button></div></form></Card></div>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-2"><Label>{label}</Label>{children}</div>}
