import { NextResponse } from "next/server";
import { getAuthenticatedUser } from "@/lib/supabase/auth";
import { createClient } from "@/lib/supabase/server";
import { sendContactEmail } from "@/lib/briitely/email";
import { BOOKING_FORM_TTL_DAYS, hashBookingFormToken, newBookingFormToken } from "@/lib/travel/booking-form";

export async function POST(request:Request,{params}:{params:Promise<{travelFileId:string}>}){
  const{user}=await getAuthenticatedUser();if(!user)return NextResponse.json({error:"Authentication required."},{status:401});if(!["staff","admin","super_admin"].includes(user.role))return NextResponse.json({error:"Staff access required."},{status:403});
  const{travelFileId}=await params;const supabase=await createClient();const{data:rawFile,error:fileError}=await supabase.from("travel_files").select(`id,stage,briitely_contact_id,client_name,destination,tmf_agreement_type,tmf_amount,revisions_included,current_action:travel_actions!current_action_id(id,action_code,status,responsible_type,responsible_user_id),assigned_advisor:profiles!assigned_advisor_id(id,full_name,ghl_user_id)`).eq("id",travelFileId).maybeSingle();if(fileError||!rawFile)return NextResponse.json({error:"Travel File not found."},{status:404});
  const file=rawFile as any,currentAction=file.current_action;if(!currentAction||currentAction.action_code!=="send_tmf_agreement")return NextResponse.json({error:"No pending Send Retainer Agreement action on this Travel File."},{status:400});if(currentAction.status==="completed")return NextResponse.json({success:true,result:"already_processed"});const isAdmin=user.role==="admin"||user.role==="super_admin",isResponsible=currentAction.responsible_type==="internal"&&currentAction.responsible_user_id===user.id;if(!isAdmin&&!isResponsible)return NextResponse.json({error:"Only the responsible user or an admin can send the Retainer Agreement."},{status:403});
  if(!file.briitely_contact_id)return NextResponse.json({error:"No Briitely contact is linked to this Travel File."},{status:400});const missing:string[]=[];if(!file.destination)missing.push("Destination");if(!file.assigned_advisor?.full_name)missing.push("Assigned Advisor");if(file.tmf_amount==null)missing.push("Retainer Amount");if(file.tmf_agreement_type==="ivt"&&file.revisions_included==null)missing.push("Revisions Included");if(missing.length)return NextResponse.json({error:`Cannot send Retainer Agreement: missing ${missing.join(", ")}.`},{status:400});
  const token=newBookingFormToken(),expiresAt=new Date(Date.now()+BOOKING_FORM_TTL_DAYS*86400000).toISOString();const{error:sessionError}=await supabase.from("booking_form_sessions").insert({travel_file_id:travelFileId,token_hash:hashBookingFormToken(token),expires_at:expiresAt,created_by:user.id,include_retainer:true});if(sessionError)return NextResponse.json({error:sessionError.message},{status:500});const origin=new URL(request.url).origin,bookingUrl=`${origin}/booking/${encodeURIComponent(token)}`;const firstName=(file.client_name||"there").trim().split(/\s+/)[0];const advisor=file.assigned_advisor.full_name;
  try{await sendContactEmail({contactId:file.briitely_contact_id,subject:"Your Retainer Agreement & Booking Information",html:`<p>Hi ${escapeHtml(firstName)},</p><p>We're ready to begin planning your ${escapeHtml(file.destination)} trip.</p><p>Please use the secure link below to review and accept your Retainer Agreement, then complete or confirm your traveller information.</p><p><a href="${escapeHtml(bookingUrl)}">Review Retainer Agreement & Booking Information</a></p><p>This secure link expires in ${BOOKING_FORM_TTL_DAYS} days.</p><p>Thank you,<br>${escapeHtml(advisor)}</p>`})}catch(error){console.error("RETAINER_EMAIL_SEND_FAILED",error);return NextResponse.json({error:"Could not send the Retainer Agreement email through Briitely. Please try again."},{status:502})}
  const now=new Date().toISOString();const{error:completeError}=await supabase.from("travel_actions").update({status:"completed",completed_at:now,completed_by:user.id,completion_source:"portal"}).eq("id",currentAction.id);if(completeError)return NextResponse.json({error:"The email was sent but the action could not be marked complete. Please contact an administrator."},{status:500});
  const{data:newAction,error:createError}=await supabase.from("travel_actions").insert({travel_file_id:travelFileId,action_code:"await_tmf_and_booking_form",title:"Await Retainer Agreement & Booking Form",action_role:"blocking",responsible_type:"client",status:"active",waiting_since:now,activated_at:now,metadata:{delivery:"portal_booking_link"}}).select("id").single();if(createError||!newAction)return NextResponse.json({error:"The email was sent but the next action could not be created. Please contact an administrator."},{status:500});
  const{error:updateError}=await supabase.from("travel_files").update({stage:"tmf_sent",stage_changed_at:now,current_action_id:newAction.id,tmf_sent_at:now,tmf_document_id:null}).eq("id",travelFileId);if(updateError)return NextResponse.json({error:"The email was sent but the Travel File could not be updated. Please contact an administrator."},{status:500});await supabase.from("travel_activity").insert({travel_file_id:travelFileId,event_type:"retainer_agreement_sent",summary:"Retainer Agreement and Booking Form link emailed to client.",actor_type:"internal",actor_user_id:user.id,action_id:currentAction.id,previous_stage:file.stage,new_stage:"tmf_sent",metadata:{delivery:"briitely_email",bookingForm:true}});return NextResponse.json({success:true,result:"sent",stage:"tmf_sent",bookingUrl,expiresAt,nextAction:{id:newAction.id,title:"Await Retainer Agreement & Booking Form",actionCode:"await_tmf_and_booking_form"}})
}
function escapeHtml(value:string){return value.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]||c))}
