import{NextResponse}from"next/server";import{createClient}from"@/lib/supabase/server";import{createClient as createSupabaseClient}from"@supabase/supabase-js";
function profile(member:any){return Array.isArray(member?.traveller_profiles)?member.traveller_profiles[0]:member?.traveller_profiles}
function first(v:string){return v.trim().split(/\s+/)[0]||"there"}
function date(v:string|null){if(!v)return"";const d=new Date(v+"T12:00:00Z");return Number.isNaN(d.getTime())?v:d.toLocaleDateString("en-CA",{month:"long",day:"numeric",year:"numeric",timeZone:"UTC"})}
function render(value:string,vars:Record<string,string>){return Object.entries(vars).reduce((s,[k,v])=>s.replaceAll(`{{${k}}}`,v),value)}
export async function POST(request:Request,{params}:{params:Promise<{travelFileId:string}>}){
 const secret=process.env.PRETRIP_EMAIL_EXECUTION_SECRET?.trim(),provided=request.headers.get("authorization")?.replace(/^Bearer\s+/i,"").trim();if(!secret||provided!==secret)return NextResponse.json({error:"Unauthorized."},{status:401});
 const{travelFileId}=await params,body=await request.json().catch(()=>null)as{email_code?:string;test?:boolean}|null,code=body?.email_code?.trim(),test=Boolean(body?.test);if(!code)return NextResponse.json({error:"email_code is required."},{status:400});
 const serviceKey=process.env.SUPABASE_SERVICE_ROLE_KEY?.trim();const db=serviceKey?createSupabaseClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,serviceKey,{auth:{persistSession:false,autoRefreshToken:false}}):await createClient();const[{data:file},{data:plan},{data:template},{data:party}]=await Promise.all([
 db.from("travel_files").select("id,client_name,destination,trip_type,departure_date,return_date,assigned_advisor_id,travefy_trip_id").eq("id",travelFileId).maybeSingle(),
 db.from("travel_pretrip_emails").select("email_code,email_name,enabled,scheduled_date,sent_at").eq("travel_file_id",travelFileId).eq("email_code",code).maybeSingle(),
 db.from("travel_email_templates").select("email_code,email_name,subject,body_html").eq("email_code",code).maybeSingle(),
 db.from("travel_file_travellers").select("id,traveller_role,receive_trip_communications,traveller_profiles:traveller_profile_id(briitely_contact_id,first_name,last_name,preferred_name,email)").eq("travel_file_id",travelFileId).order("created_at",{ascending:true})
 ]);if(!file)return NextResponse.json({error:"Travel File not found.",diagnostic:{travelFileId,serviceRoleConfigured:Boolean(serviceKey),supabaseUrlConfigured:Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL)}},{status:404});if(!plan||!plan.enabled)return NextResponse.json({error:"This scheduled email is not enabled.",diagnostic:{travelFileId,emailCode:code,fileFound:Boolean(file),planFound:Boolean(plan),serviceRoleConfigured:Boolean(serviceKey)}},{status:409});if(plan.sent_at&&!test)return NextResponse.json({success:true,alreadySent:true});if(!template?.subject?.trim()||!template?.body_html?.trim())return NextResponse.json({error:"The email template is blank."},{status:409});if(template.email_code!==code)return NextResponse.json({error:`Template mismatch: requested ${code} but loaded ${template.email_code}.`},{status:409});
 const recipients=(party??[]).filter((m:any)=>m.traveller_role==="primary"||m.receive_trip_communications).map((m:any)=>{const p=profile(m);return{contact_id:p?.briitely_contact_id??null,name:[p?.preferred_name||p?.first_name,p?.last_name].filter(Boolean).join(" ")||"Client",first_name:p?.preferred_name||p?.first_name||"there",email:p?.email?.trim()||null}}).filter((r:any)=>r.email);if(!recipients.length)return NextResponse.json({error:"No trip communication recipients have an email address."},{status:409});
 const webhook=process.env.BRIITELY_TRIP_EMAIL_WEBHOOK_URL?.trim();if(!webhook)return NextResponse.json({error:"BRIITELY_TRIP_EMAIL_WEBHOOK_URL is not configured."},{status:500});
 for(const r of recipients){const vars={first_name:r.first_name,destination:file.destination??"your upcoming trip",departure_date:date(file.departure_date),return_date:date(file.return_date),travefy_trip_plan_url:file.travefy_trip_id??""};const payload={event:"travel_file_client_email",email_type:code,contact_id:r.contact_id,contact_name:r.name,email:r.email,travel_file_id:file.id,destination:file.destination,trip_type:file.trip_type,departure_date:file.departure_date,return_date:file.return_date,assigned_advisor_id:file.assigned_advisor_id,email_subject:render(template.subject,vars),email_html:render(template.body_html,vars)};const response=await fetch(webhook,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload),cache:"no-store"});if(!response.ok)return NextResponse.json({error:`Briitely email webhook returned ${response.status} while sending to ${r.email}.`},{status:502})}
 const now=new Date().toISOString();if(test)return NextResponse.json({success:true,test:true,emailCode:code,templateCode:template.email_code,templateSubject:template.subject,recipientCount:recipients.length});const{data:marked,error:markError}=await db.from("travel_pretrip_emails").update({sent_at:now}).eq("travel_file_id",travelFileId).eq("email_code",code).is("sent_at",null).select("email_code").maybeSingle();if(markError||!marked)return NextResponse.json({error:markError?.message??"Email was delivered, but the schedule could not be marked sent."},{status:500});const{error:activityError}=await db.from("travel_activity").insert({travel_file_id:travelFileId,event_type:"scheduled_trip_email_sent",summary:`${template.email_name} sent through Briitely to ${recipients.length} recipient${recipients.length===1?"":"s"}.`,actor_type:"system",metadata:{email_code:code,recipient_count:recipients.length,scheduled_date:plan.scheduled_date,template_code:template.email_code,template_subject:template.subject}});if(activityError)return NextResponse.json({error:`Email was delivered and marked sent, but activity logging failed: ${activityError.message}`},{status:500});return NextResponse.json({success:true,emailCode:code,templateCode:template.email_code,templateSubject:template.subject,recipientCount:recipients.length,sentAt:now})
}