import{NextResponse}from"next/server";import{getAuthenticatedUser}from"@/lib/supabase/auth";import{createClient}from"@/lib/supabase/server";import{getContactCustomFieldDefinitions,updateContactCustomField}from"@/lib/briitely/contact-custom-fields";
const FIELD_NAMES:Record<string,string>={trip_plans_sent:"TripPlans Has Been Sent",insurance:"Insurance",seat_selection:"Seat Selection",vaccines_visas:"Vaccines & Visas",destination_spending:"In-Destination Spending",pre_trip_pamper:"Pre-Trip Pamper",staying_connected:"Staying Connected",final_countdown:"Final Countdown",luggage_packing:"Luggage & Packing Tips",almost_time:"Almost Time to Go",welcome_home:"Welcome Home"};
function profile(m:any){return Array.isArray(m?.traveller_profiles)?m.traveller_profiles[0]:m?.traveller_profiles}
export async function POST(_r:Request,{params}:{params:Promise<{travelFileId:string}>}){const{user}=await getAuthenticatedUser();if(!user||!user.isActive||!["staff","admin","super_admin"].includes(user.role))return NextResponse.json({error:"Authentication required."},{status:401});const db=await createClient(),{travelFileId}=await params;
const[{data:emails,error:emailError},{data:party,error:partyError}]=await Promise.all([db.from("travel_pretrip_emails").select("email_code,enabled,scheduled_date").eq("travel_file_id",travelFileId),db.from("travel_file_travellers").select("traveller_role,receive_trip_communications,traveller_profiles:traveller_profile_id(briitely_contact_id,email)").eq("travel_file_id",travelFileId)]);
if(emailError||partyError)return NextResponse.json({error:"Could not load the email schedule or travellers."},{status:500});
const recipients=(party??[]).filter((m:any)=>m.traveller_role==="primary"||m.receive_trip_communications).map((m:any)=>profile(m)).filter((p:any)=>p?.briitely_contact_id&&p?.email);
if(!recipients.length)return NextResponse.json({error:"No trip communication recipients are connected to Briitely."},{status:400});
const defs=await getContactCustomFieldDefinitions();if(defs.errorMessage)return NextResponse.json({error:`Could not load Briitely custom fields: ${defs.errorMessage}`},{status:502});const byName=new Map(defs.definitions.map(d=>[d.name,d]));const missing=Object.values(FIELD_NAMES).filter(n=>!byName.has(n));if(missing.length)return NextResponse.json({error:`Missing Briitely custom field${missing.length===1?"":"s"}: ${missing.join(", ")}`},{status:400});
const schedule=new Map((emails??[]).map((e:any)=>[e.email_code,e]));const failures:string[]=[];for(const p of recipients){for(const[code,name]of Object.entries(FIELD_NAMES)){const d=byName.get(name)!;const e:any=schedule.get(code);const value=e?.enabled&&e?.scheduled_date?e.scheduled_date:null;const result=await updateContactCustomField(p.briitely_contact_id,d.id,d.fieldKey,value);if(!result.succeeded)failures.push(`${p.email}: ${name}`)}}}
if(failures.length)return NextResponse.json({error:`Schedule saved, but some Briitely fields could not be updated: ${failures.slice(0,4).join(", ")}${failures.length>4?"…":""}`},{status:502});
await db.from("travel_activity").insert({travel_file_id:travelFileId,event_type:"pretrip_email_schedule_synced",summary:`Pre-trip email schedule synced to Briitely for ${recipients.length} recipient${recipients.length===1?"":"s"}.`,actor_type:"internal",actor_user_id:user.id,metadata:{recipient_count:recipients.length}});
return NextResponse.json({success:true,recipientCount:recipients.length})}