import{NextResponse}from"next/server";import{getAuthenticatedUser}from"@/lib/supabase/auth";import{createClient}from"@/lib/supabase/server";
const DEFINITIONS=[
{code:"trip_plans_sent",name:"TripPlans Has Been Sent",note:"When TripPlans itinerary is sent",kind:"today",days:0},
{code:"insurance",name:"Insurance",note:"1 day after TripPlans is sent",kind:"today",days:1},
{code:"seat_selection",name:"Seat Selection",note:"1 week after TripPlans is sent",kind:"today",days:7},
{code:"vaccines_visas",name:"Vaccines & Visas",note:"180 days before departure",kind:"departure",days:-180},
{code:"destination_spending",name:"In-Destination Spending",note:"75 days before departure",kind:"departure",days:-75},
{code:"pre_trip_pamper",name:"Pre-Trip Pamper",note:"60 days before departure",kind:"departure",days:-60},
{code:"staying_connected",name:"Staying Connected",note:"45 days before departure",kind:"departure",days:-45},
{code:"final_countdown",name:"Final Countdown",note:"30 days before departure",kind:"departure",days:-30},
{code:"luggage_packing",name:"Luggage & Packing Tips",note:"14 days before departure",kind:"departure",days:-14},
{code:"almost_time",name:"Almost Time to Go",note:"2 days before departure",kind:"departure",days:-2},
{code:"welcome_home",name:"Welcome Home",note:"3 days after return",kind:"return",days:3},
]as const;
async function ctx(){const{user}=await getAuthenticatedUser();if(!user||!user.isActive||!["staff","admin","super_admin"].includes(user.role))return null;return{user,db:await createClient()}}
function shift(base:string|null,days:number){if(!base)return null;const d=new Date(`${base}T12:00:00.000Z`);if(Number.isNaN(d.getTime()))return null;d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10)}
function today(){return new Date().toISOString().slice(0,10)}
export async function GET(_r:Request,{params}:{params:Promise<{travelFileId:string}>}){const c=await ctx();if(!c)return NextResponse.json({error:"Authentication required."},{status:401});const{travelFileId}=await params;const[{data:file,error:fileError},{data:existing,error:planError}]=await Promise.all([c.db.from("travel_files").select("departure_date,return_date").eq("id",travelFileId).maybeSingle(),c.db.from("travel_pretrip_emails").select("email_code,email_name,enabled,scheduled_date,timing_note,sequence_order,sent_at").eq("travel_file_id",travelFileId).order("sequence_order",{ascending:true})]);if(fileError||!file)return NextResponse.json({error:"Travel File not found."},{status:404});if(planError)return NextResponse.json({error:"Could not load the pre-trip email plan."},{status:500});const byCode=new Map((existing??[]).map((x:any)=>[x.email_code,x]));const baseToday=today();const emails=DEFINITIONS.map((d,i)=>{const saved:any=byCode.get(d.code);const base=d.kind==="departure"?file.departure_date:d.kind==="return"?file.return_date:baseToday;return saved??{email_code:d.code,email_name:d.name,enabled:true,scheduled_date:shift(base,d.days),timing_note:d.note,sequence_order:i+1,sent_at:null}});return NextResponse.json({departureDate:file.departure_date,returnDate:file.return_date,emails})}
export async function POST(request:Request,{params}:{params:Promise<{travelFileId:string}>}){const c=await ctx();if(!c)return NextResponse.json({error:"Authentication required."},{status:401});const{travelFileId}=await params;const body=await request.json().catch(()=>null)as{emails?:Array<{email_code:string;enabled:boolean;scheduled_date:string|null}>}|null;if(!Array.isArray(body?.emails))return NextResponse.json({error:"Email schedule is required."},{status:400});const allowed=new Map(DEFINITIONS.map((d,i)=>[d.code,{...d,order:i+1}]));const rows=[];for(const item of body.emails){const d=allowed.get(item.email_code);if(!d)continue;if(item.enabled&&!item.scheduled_date)return NextResponse.json({error:`Choose a send date for ${d.name}.`},{status:400});rows.push({travel_file_id:travelFileId,email_code:d.code,email_name:d.name,enabled:Boolean(item.enabled),scheduled_date:item.scheduled_date||null,timing_note:d.note,sequence_order:d.order})}const{error}=await c.db.from("travel_pretrip_emails").upsert(rows,{onConflict:"travel_file_id,email_code"});if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({saved:true})}
