import {NextResponse} from "next/server";
import {getAuthenticatedUser} from "@/lib/supabase/auth";
import {createClient} from "@/lib/supabase/server";

async function ctx(){const{user,error}=await getAuthenticatedUser();if(error||!user||!user.isActive)return null;return{user,supabase:await createClient()}}
export async function GET(_req:Request,{params}:{params:Promise<{travelFileId:string}>}){const{travelFileId}=await params;const c=await ctx();if(!c)return NextResponse.json({error:"Unauthorized"},{status:401});const[{data,error},{data:profiles}]=await Promise.all([c.supabase.from("travel_file_tasks").select("id,title,notes,assigned_to,due_date,status,created_by,completed_at,completed_by,created_at,updated_at,assigned_profile:profiles!assigned_to(id,full_name),completed_profile:profiles!completed_by(id,full_name)").eq("travel_file_id",travelFileId).order("status",{ascending:false}).order("due_date",{ascending:true,nullsFirst:false}).order("created_at",{ascending:true}),c.supabase.from("profiles").select("id,full_name").eq("is_active",true).order("full_name")]);if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({tasks:data??[],profiles:profiles??[]})}
export async function POST(req:Request,{params}:{params:Promise<{travelFileId:string}>}){const{travelFileId}=await params;const c=await ctx();if(!c)return NextResponse.json({error:"Unauthorized"},{status:401});const b=await req.json().catch(()=>null) as {title?:string;notes?:string;assignedTo?:string|null;dueDate?:string|null}|null;const title=b?.title?.trim();if(!title)return NextResponse.json({error:"Task is required."},{status:400});const{data,error}=await c.supabase.from("travel_file_tasks").insert({travel_file_id:travelFileId,title,notes:b?.notes?.trim()||null,assigned_to:b?.assignedTo||null,due_date:b?.dueDate||null,created_by:c.user.id}).select("id").single();if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({task:data},{status:201})}
export async function PATCH(req:Request,{params}:{params:Promise<{travelFileId:string}>}){const{travelFileId}=await params;const c=await ctx();if(!c)return NextResponse.json({error:"Unauthorized"},{status:401});const b=await req.json().catch(()=>null) as {taskId?:string;title?:string;notes?:string|null;assignedTo?:string|null;dueDate?:string|null;status?:"todo"|"in_progress"|"complete"}|null;if(!b?.taskId)return NextResponse.json({error:"Task is required."},{status:400});const updates:any={updated_at:new Date().toISOString()};if(b.title!==undefined){if(!b.title.trim())return NextResponse.json({error:"Task is required."},{status:400});updates.title=b.title.trim()}if(b.notes!==undefined)updates.notes=b.notes?.trim()||null;if(b.assignedTo!==undefined)updates.assigned_to=b.assignedTo||null;if(b.dueDate!==undefined)updates.due_date=b.dueDate||null;if(b.status!==undefined){updates.status=b.status;if(b.status==="complete"){updates.completed_at=new Date().toISOString();updates.completed_by=c.user.id}else{updates.completed_at=null;updates.completed_by=null}}const{error}=await c.supabase.from("travel_file_tasks").update(updates).eq("id",b.taskId).eq("travel_file_id",travelFileId);if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({updated:true})}
export async function DELETE(req:Request,{params}:{params:Promise<{travelFileId:string}>}){const{travelFileId}=await params;const c=await ctx();if(!c)return NextResponse.json({error:"Unauthorized"},{status:401});const b=await req.json().catch(()=>null) as {taskId?:string}|null;if(!b?.taskId)return NextResponse.json({error:"Task is required."},{status:400});const{error}=await c.supabase.from("travel_file_tasks").delete().eq("id",b.taskId).eq("travel_file_id",travelFileId);if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({deleted:true})}
