import{NextResponse}from"next/server";import{getAuthenticatedUser}from"@/lib/supabase/auth";import{createClient}from"@/lib/supabase/server";
export async function POST(_request:Request,{params}:{params:Promise<{travelFileId:string}>}){
 const{user}=await getAuthenticatedUser();if(!user||!user.isActive)return NextResponse.json({error:"Authentication required."},{status:401});if(!["staff","admin","super_admin"].includes(user.role))return NextResponse.json({error:"Staff access required."},{status:403});
 const{travelFileId}=await params,db=await createClient();const{data:file,error}=await db.from("travel_files").select("id,stage,current_action_id,file_status,current_action:travel_actions!current_action_id(id,action_code,status)").eq("id",travelFileId).maybeSingle();if(error||!file)return NextResponse.json({error:"Travel File not found."},{status:404});
 const current=Array.isArray(file.current_action)?file.current_action[0]:file.current_action;if(file.file_status==="closed")return NextResponse.json({success:true,alreadyClosed:true});if(!current||current.action_code!=="post_trip_close_file"||current.status!=="active")return NextResponse.json({error:"Post-Trip / Close File is not the active action."},{status:409});
 const now=new Date().toISOString();const{error:actionError}=await db.from("travel_actions").update({status:"completed",completed_at:now,completed_by:user.id,completion_source:"portal",completion_event:"travel_file_closed"}).eq("id",current.id);if(actionError)return NextResponse.json({error:"Could not complete the post-trip action."},{status:500});
 const{error:fileError}=await db.from("travel_files").update({file_status:"closed",stage:"travel_complete",stage_changed_at:now,current_action_id:null,closed_at:now}).eq("id",travelFileId);if(fileError)return NextResponse.json({error:"Could not close the Travel File."},{status:500});
 await db.from("travel_activity").insert({travel_file_id:travelFileId,event_type:"travel_file_closed",summary:"Post-trip follow-up completed. Travel File closed and moved to Past Trips.",actor_type:"internal",actor_user_id:user.id,action_id:current.id,previous_stage:file.stage,new_stage:"travel_complete",metadata:{}});
 return NextResponse.json({success:true,stage:"travel_complete"});
}