INSERT INTO public.travel_email_templates(email_code,email_name,subject,body_html) VALUES
('proposal_initial','Proposal – Initial Send','🌴 Your Custom Trip Proposal is Ready! ✈️','<p>Hi {{first_name}},</p><p>Exciting news — your personalized travel proposal is ready! 🎉 We''ve crafted it just for you, packed with options and ideas to make your trip unforgettable.</p><p>You should also see it from Travefy in your inbox. If it doesn''t appear, please check your spam or junk folder.</p><p>👉 <a href="{{travefy_proposal_url}}">View Your Custom Trip Proposal</a></p><p>Take your time to explore it, and if you have any questions, want to tweak something, or just want to chat about your options, we''re here and happy to help. Just hit reply on this email and we''ll get back to you! 🌺</p><p>We can''t wait to hear what you think!</p><p>Cheers,</p><p>{{advisor_first_name}} &amp; the Inspired Vacations Team ✈️</p>'),
('proposal_resend','Proposal – Resend / Reminder','🌴 Your Custom Trip Proposal is Ready! ✈️','<p>Hi {{first_name}},</p><p>Just a quick follow-up — we''re resending the link to your personalized travel proposal so it''s easy to find.</p><p>👉 <a href="{{travefy_proposal_url}}">View Your Custom Trip Proposal</a></p><p>Take your time to explore it, and if you have any questions, want to tweak something, or just want to chat about your options, we''re here and happy to help. Just hit reply on this email and we''ll get back to you! 🌺</p><p>Cheers,</p><p>{{advisor_first_name}} &amp; the Inspired Vacations Team ✈️</p>'),
('retainer_booking_form','Retainer Agreement + Booking Form','Your Retainer Agreement & Booking Information - Inspired Vacations','<p>Hi {{first_name}},</p><p>Your Retainer Agreement is ready. Please use the secure link below to review and sign it and then complete the Client Booking Form.</p><p>This form provides all details we need to hit the ground running, including personal and passport details, special considerations we need to accommodate, emergency contact information, and payment authorization.</p><p>👉 <a href="{{secure_form_url}}">Review Your Agreement &amp; Complete Your Booking Form</a></p><p>Once we have your completed forms, we can get to work planning! ✈️</p><p>If you have any questions, just hit reply — we''re always happy to help. 😊</p><p>Cheers,</p><p>{{advisor_first_name}} &amp; the Inspired Vacations Team 🌺</p>'),
('primary_booking_form_reminder','Booking Form – Primary Reminder','Your Client Booking Form - Inspired Vacations','<p>Hi {{first_name}},</p><p>Here''s a fresh link to your Client Booking Form. Your Retainer Agreement has already been completed, so you do not need to sign it again.</p><p>👉 <a href="{{secure_form_url}}">Complete Your Booking Form</a></p><p>If you have any questions, just hit reply — we''re always happy to help. 😊</p><p>Cheers,</p><p>{{advisor_first_name}} &amp; the Inspired Vacations Team 🌺</p>'),
('additional_traveller_booking_form','Booking Form – Additional Traveller','Your Booking Form for Your {{destination}} Trip with {{primary_first_name}}','<p>Hi {{first_name}},</p><p>We''re excited to book this trip to {{destination}} for you and {{primary_first_name}}! Before we can get started, please take a few minutes to complete your Client Booking Form using the link below.</p><p>👉 <a href="{{secure_form_url}}">Complete Your Booking Form</a></p><p>What''s included:</p><p>• Personal and passport details<br>• Special considerations<br>• Emergency contact information</p><p>If you have any questions, just hit reply — we''re always happy to help. 😊</p><p>Cheers,</p><p>{{advisor_first_name}} &amp; the Inspired Vacations Team 🌺</p>'),
('insurance','Insurance','',''),
('seat_selection','Seat Selection','',''),
('vaccines_visas','Vaccines & Visas','',''),
('destination_spending','In-Destination Spending','',''),
('pre_trip_pamper','Pre-Trip Pamper','',''),
('staying_connected','Staying Connected','',''),
('final_countdown','Final Countdown','',''),
('luggage_packing','Luggage & Packing Tips','',''),
('almost_time','Almost Time to Go','',''),
('welcome_home','Welcome Home','','')
ON CONFLICT(email_code) DO NOTHING;
