import { NextResponse } from "next/server";
import { getAuthenticatedUser } from "@/lib/supabase/auth";
import { createClient } from "@/lib/supabase/server";
import { createTravelNote } from "@/lib/travel/notes-service";
import { clientConfig } from "@/config/client.config";

interface CompleteConsultationBody {isFit:"yes"|"no";destination?:string|null;tripType?:string|null;travelTimeframe?:string|null;departureDate?:string|null;returnDate?:string|null;budgetRange?:string|null;specialConsiderations?:string|null;insuranceInterest?:string|null;consultationNote?:string|null;consultationNoteType?:"client_facing"|"internal";agreementType?:"ivt"|"all_inclusive";tmfAmount?:number;assignedAdvisorId?:string;revisionsIncluded?:number;notFitReason?:string}

export async function POST(request:Request,{params}:{params:Promise<{travelFileId:string}>}){
 const{user}=await getAuthenticatedUser();if(!user)return NextResponse.json({error:"Authentication required."},{status:401});if(user.role!=="staff"&&user.role!=="admin"&&user.role!=="super_admin")return NextResponse.json({error:"Staff access required."},{status:403});
 const{travelFileId}=await params;let body:CompleteConsultationBody;try{body=await request.json() as CompleteConsultationBody}catch{return NextResponse.json({error:"Invalid request body."},{status:400})}if(!body.isFit||(body.isFit!=="yes"&&body.isFit!=="no"))return NextResponse.json({error:"Is this client a fit? is required."},{status:400});
 const supabase=await createClient();const{data:rawFile,error:fileError}=await supabase.from("travel_files").select(`*, current_action:travel_actions!current_action_id (*)`).eq("id",travelFileId).maybeSingle();if(fileError||!rawFile)return NextResponse.json({error:"Travel File not found."},{status:404});
 const file=rawFile as Record<string,unknown>&{id:string;stage:string;current_action:{id:string;action_code:string;status:string}|null};let currentAction=file.current_action;if(!currentAction&&file.stage==="consult_booked"){const{data:fallback}=await supabase.from("travel_actions").select("id, action_code, title, status").eq("travel_file_id",travelFileId).eq("action_code","complete_initial_consultation").neq("status","completed").order("created_at",{ascending:false}).limit(1).maybeSingle();if(fallback)currentAction=fallback as typeof currentAction}if(!currentAction||currentAction.action_code!=="complete_initial_consultation")return NextResponse.json({error:"No pending initial consultation action on this Travel File."},{status:400});if(currentAction.status==="completed")return NextResponse.json({success:true,result:"already_processed",message:"Consultation has already been completed for this Travel File."});

 const{data:party,error:partyError}=await supabase.from("travel_file_travellers").select("id, relationship_to_primary").eq("travel_file_id",travelFileId);if(partyError)return NextResponse.json({error:"Could not read the Travel Party."},{status:500});const travellerTotal=party?.length??0;const childCount=(party??[]).filter(m=>m.relationship_to_primary==="child").length;const adultCount=Math.max(0,travellerTotal-childCount);if(travellerTotal<1)return NextResponse.json({error:"Add at least one traveller to the Travel Party."},{status:400});
 if(body.departureDate&&body.returnDate&&new Date(body.returnDate+"T00:00:00")<new Date(body.departureDate+"T00:00:00"))return NextResponse.json({error:"Return date cannot be before departure date."},{status:400});if(!body.insuranceInterest?.trim())return NextResponse.json({error:"Travel Insurance preference is required."},{status:400});if(body.isFit==="no"&&!body.notFitReason?.trim())return NextResponse.json({error:"Reason / Notes is required when client is not a fit."},{status:400});
 let agreementType:"ivt"|"all_inclusive"|null=null,tmfAmount:number|null=null,assignedAdvisorId:string|null=null,revisionsIncluded:number|null=null;if(body.isFit==="yes"){if(!body.agreementType||(body.agreementType!=="ivt"&&body.agreementType!=="all_inclusive"))return NextResponse.json({error:"Agreement / trip category is required (IVT or All-Inclusive)."},{status:400});agreementType=body.agreementType;tmfAmount=body.tmfAmount??null;if(tmfAmount==null||isNaN(tmfAmount)||tmfAmount<0)return NextResponse.json({error:"Retainer Amount is required and must be a valid non-negative number."},{status:400});if(!body.assignedAdvisorId)return NextResponse.json({error:"Assigned Advisor is required."},{status:400});assignedAdvisorId=body.assignedAdvisorId;if(agreementType==="ivt"){if(body.revisionsIncluded==null||!Number.isInteger(body.revisionsIncluded)||body.revisionsIncluded<0)return NextResponse.json({error:"Number of Revisions Included is required for IVT agreements and must be a non-negative integer."},{status:400});revisionsIncluded=body.revisionsIncluded}}
 const now=new Date().toISOString();const fileUpdate:Record<string,unknown>={destination:body.destination??null,trip_type:body.tripType??null,travel_timeframe:body.travelTimeframe??null,departure_date:body.departureDate??null,return_date:body.returnDate??null,number_of_adults:adultCount,number_of_children:childCount,children_ages:null,number_of_travellers:travellerTotal,budget_range:body.budgetRange??null,special_requests:body.specialConsiderations??null,insurance_interest:body.insuranceInterest??null};
 if(body.isFit==="no"){const{error:consultError}=await supabase.from("travel_consultations").insert({travel_file_id:travelFileId,conducted_by:user.id,outcome:"not_fit",discussion_summary:body.notFitReason!.trim(),destination:body.destination??null,trip_type:body.tripType??null,number_of_travellers:travellerTotal,departure_date:body.departureDate??null,return_date:body.returnDate??null,budget_range:body.budgetRange??null});if(consultError)return NextResponse.json({error:"Failed to save consultation record."},{status:500});const{error:actionError}=await supabase.from("travel_actions").update({status:"completed",completed_at:now,completed_by:user.id,completion_source:"portal"}).eq("id",currentAction.id);if(actionError)return NextResponse.json({error:"Failed to complete consultation action."},{status:500});Object.assign(fileUpdate,{stage:"lost_not_qualified",file_status:"closed",closed_at:now,lost_reason:body.notFitReason!.trim(),current_action_id:null,stage_changed_at:now});const{error:updateError}=await supabase.from("travel_files").update(fileUpdate).eq("id",travelFileId);if(updateError)return NextResponse.json({error:"Failed to update Travel File."},{status:500});await supabase.from("travel_activity").insert({travel_file_id:travelFileId,event_type:"consultation_completed",summary:"Initial consultation completed. Client was not a fit.",actor_type:"internal",actor_user_id:user.id,action_id:currentAction.id,previous_stage:file.stage,new_stage:"lost_not_qualified"});if(body.consultationNote?.trim()){const note=await createTravelNote(supabase,{travelFileId,noteType:body.consultationNoteType==="client_facing"?"client_facing":"internal",noteText:body.consultationNote.trim(),createdBy:user.id});if(!note.success)return NextResponse.json({error:"Consultation was saved but the note could not be created. Please add the note manually from the Notes card."},{status:500})}return NextResponse.json({success:true,stage:"lost_not_qualified"})}
 const retainerOwnerId=process.env.DEFAULT_TMF_OWNER_PROFILE_ID||clientConfig.defaultTmfOwnerProfileId||null;const{data:newAction,error:actionCreateError}=await supabase.from("travel_actions").insert({travel_file_id:travelFileId,action_code:"send_tmf_agreement",title:"Send Retainer Agreement",action_role:"blocking",responsible_type:"internal",responsible_user_id:retainerOwnerId,status:"active",waiting_since:now}).select().single();if(actionCreateError||!newAction)return NextResponse.json({error:"Failed to create next action."},{status:500});
 const{error:consultError}=await supabase.from("travel_consultations").insert({travel_file_id:travelFileId,conducted_by:user.id,outcome:"proceed",destination:body.destination??null,trip_type:body.tripType??null,number_of_travellers:travellerTotal,departure_date:body.departureDate??null,return_date:body.returnDate??null,budget_range:body.budgetRange??null,tmf_amount:tmfAmount,ivt_custom:agreementType==="ivt",assigned_advisor_id:assignedAdvisorId,revisions_allowed:revisionsIncluded});if(consultError){await supabase.from("travel_actions").delete().eq("id",newAction.id);return NextResponse.json({error:"Failed to save consultation record."},{status:500})}
 const{error:actionCompleteError}=await supabase.from("travel_actions").update({status:"completed",completed_at:now,completed_by:user.id,completion_source:"portal"}).eq("id",currentAction.id);if(actionCompleteError){await supabase.from("travel_actions").delete().eq("id",newAction.id);return NextResponse.json({error:"Failed to complete consultation action."},{status:500})}
 Object.assign(fileUpdate,{stage:"consultation_complete",stage_changed_at:now,assigned_advisor_id:assignedAdvisorId,tmf_amount:tmfAmount,tmf_agreement_type:agreementType,revisions_included:revisionsIncluded,revisions_allowed:revisionsIncluded,ivt_custom:agreementType==="ivt",current_action_id:newAction.id});const{error:fileUpdateError}=await supabase.from("travel_files").update(fileUpdate).eq("id",travelFileId);if(fileUpdateError){await supabase.from("travel_actions").delete().eq("id",newAction.id);await supabase.from("travel_actions").update({status:"active",completed_at:null,completed_by:null,completion_source:null}).eq("id",currentAction.id);return NextResponse.json({error:"Failed to update Travel File."},{status:500})}
 await supabase.from("travel_activity").insert([{travel_file_id:travelFileId,event_type:"consultation_completed",summary:"Initial consultation completed. Client proceeding.",actor_type:"internal",actor_user_id:user.id,action_id:currentAction.id,previous_stage:file.stage,new_stage:"consultation_complete"},{travel_file_id:travelFileId,event_type:"tmf_agreement_assigned",summary:retainerOwnerId?"Retainer Agreement assigned to Dana.":"Retainer Agreement action created (unassigned).",actor_type:"internal",actor_user_id:user.id,action_id:newAction.id}]);if(body.consultationNote?.trim()){const note=await createTravelNote(supabase,{travelFileId,noteType:body.consultationNoteType==="client_facing"?"client_facing":"internal",noteText:body.consultationNote.trim(),createdBy:user.id});if(!note.success)return NextResponse.json({error:"Consultation was saved but the note could not be created. Please add the note manually from the Notes card."},{status:500})}return NextResponse.json({success:true,stage:"consultation_complete",nextAction:{id:newAction.id,title:newAction.title}})
}
